# -*- coding: utf-8 -*-
"""Keven Escovedo - 20201_Est_Repeticao_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s6m7TE5DXZiGM_uWnmpNY2Jj-uRIX3xU

###1. Faça um algoritmo  que mostre 10 vezes a frase “Bem vindo a Fatec!”.
"""

contador = 0;
while (contador < 10):
      contador += 1;
      print(contador,"Bem vindo a fatec")
# for x in range(11):
      #print(contador,"Bem vindo a fatec")

"""###2. Faça um algoritmo que mostre o cumprimento ‘Olá ‘ para o nome de alguém (4 pessoas). Exemplo ‘Olá Mariana’."""

for ola in range(4):
  name = input("Digite seu nome por favor:\n")
  print("OLÁ",name)
#while
print("WHILE")
ola = 0
while(ola < 4):
  name = input("Digite seu nome por favor:\n")
  print("OLÁ",name)
  ola += 1

"""###3. Faça um algoritmo que mostre os valores de 0 a 15."""

for x in range(16):
  
  print(x)
#while
print("WHILE")
x= 0
while(x <= 15):
   print(x)
   x = x +1

"""###4. Faça um algoritmo que mostre os valores de 3 a 20."""

for x in range(3,21):
  
  print(x)
#while
print("WHILE")
x= 3
while(x <= 20):
   print(x)
   x = x +1

"""###5. Faça um algoritmo que calcule e mostre a tabuada do 5."""

for x in range(11):
  
  print("5 x", x,"=",5 * x)
#while
print("WHILE")
x= 0
while(x <= 10):
    print("5 x", x,"=",5 * x)
    x += 1

"""###6. Faça um algoritmo que receba a idade de 10 pessoas, calcule e exiba a quantidade de pessoas maiores de idade, sendo que a maioridade é obtida após completar 18 anos."""

maior_de_idade = 0;
 contador = 0;
 for contador in range(10):
  idade = int(input("Insira sua idade por favor :\n"))
   if idade >= 18:
    maior_de_idade =  maior_de_idade + 1;
 print("A",maior_de_idade,"pessoas maiores de idade")
#while
print("while")
while(contador  <= 9):
     idade = int(input("Insira sua idade por favor :\n"))
     if idade >= 18:
        maior_de_idade =  maior_de_idade + 1;
     contador = contador + 1;
print("A",maior_de_idade,"pessoas maiores de idade")

"""###7. Escreva um algoritmo que receba 23 números, calcule e exiba a quantidade de números pares e impares."""

qtd_impares = 0;
for x in range(23):
  numero = int(input("Por favor digite um numero: \n"))
  if numero % 2 == 0:
    qtd_pares = qtd_pares + 1;
  else:
    qtd_impares = qtd_impares + 1;
print("Á", qtd_pares,"de números pares")
print("Á", qtd_impares,"de números impares")

"""###8. Faça um algoritmo que calcule e exiba o salário reajustado de dez funcionários de acordo com a seguinte regra: 
Salário até 300, reajuste de 50%; 

Salários maiores que 300, reajuste de 30%.
"""

for x in range(10):
   nome = input("Digite o nome do funcionário:\n")
   salario = float(input("digite o salario do funcionario:\n"))
   if salario <= 300:
     reajuste = salario * (50/100)
     salario_reajustado =  salario + reajuste
     print(nome,"tem um reajuste de 50 % no seu salário que será de:", salario_reajustado,"reais")
   else:
     reajuste = salario * (30/100)
     salario_reajustado =  salario + reajuste
     print(nome,"tem um reajuste de 30 % no seu salário que será de:", salario_reajustado,"reais")

"""###9. Faça um algoritmo que conheça 4 valores diferentes, some-os e mostre o resultado."""

contador = 0;
soma = 0;
soma2  =  0;
while(contador < 4):
  numero = float(input("digite um numero por favor:"))
  soma += numero
  contador = contador + 1;
print(soma)
#for
for x in range(4):
   numero = float(input("digite um numero por favor:"))
   soma2 += numero
print(soma2)

"""###10. Elabore um algoritmo que calcule e informe a média de idades de 5 alunos."""

contador = 0;
soma = 0;
soma2 = 0;
idade2  = 0;
media = 0;
media2 = 0;
 
while(contador < 5):
  idade = float(input("digite uma idade por favor"))
  soma += idade
  media = soma/5
  contador = contador + 1;
#for
print(round(media))
for x in range(5):
  idade2 = float(input("digite uma idade por favor"))
  soma2 += idade2
  media2 = soma2/5
print(round(media2))

"""###11. Construir um algoritmo para calcular a média aritmética de preços de 5 produtos."""

contador = 0;
soma = 0;
soma2 = 0;
preco2  = 0;
media = 0;
preco = 0;
 
while(contador < 5):
  preco = float(input("digite o preço por favor:\n"))
  soma += preco
  media = soma/5
  contador = contador + 1;
#for
print((media)
for x in range(5):
  idade2 = float(input("digite uma idade por favor:\n"))
  soma2 += preco2
  media2 = soma2/5
print(media2)

"""###12. Construir um algoritmo que, dado o valor de 20 preços de TV, determine e apresente o valor mais caro e mais barato entre eles."""

maior = 0
menor = 0
contador = 0;
for i in range(20):
   preco = float(input("Digite um preço da TV: "))
   maior = maior if maior != None and maior >  preco else preco
   menor = menor if menor != None and menor <  preco else preco

print ('O maior  preço é {} e o menor é {}'.format(maior,menor))
#while
while contador < 20:
  preco = float(input("Digite um preço da TV: "))
   maior = maior if maior != None and maior >  preco else preco
   menor = menor if menor != None and menor <  preco else preco
   contador = contador + 1;
print ('O maior  preço é {} e o menor é {}'.format(maior,menor))

"""###13. Faça um algoritmo que leia de dez alunos altura e nome.  Mostre o aluno mais alto e mais baixo e seus respectivos nomes."""

nome_aluno = 0;
contador = 0;
altura = 0;
altura_maior = 0;
altura_menor = 0;
nome_maior = 0;
nome_menor = 0;
for contador in range(10):
  nome = input("digite o nome do aluno:\n")
  altura = float(input("Digite a altura do aluno:\n"))

  if contador == 0:
    altura_maior = altura
    nome_maior = nome
    altura_menor = altura
    nome_menor = nome
  else:
    if altura > altura_maior:
        altura_maior = altura
        nome_maior = nome
            
    elif altura < altura_menor:
            altura_menor = altura
            nome_menor = nome
print(nome_maior,"tem",altura_maior,"por isso tem altura maior")
print(nome_menor,"tem",altura_menor,"por isso tem altura menor")
#while
print("while")
while contador < 10:
  nome = input("digite o nome do aluno:\n")
  altura = float(input("Digite a altura do aluno:\n"))

  if contador == 0:
    altura_maior = altura
    nome_maior = nome
    altura_menor = altura
    nome_menor = nome
  else:
    if altura > altura_maior:
        altura_maior = altura
        nome_maior = nome
            
    elif altura < altura_menor:
            altura_menor = altura
            nome_menor = nome
print(nome_maior,"tem",altura_maior,"por isso tem altura maior")
print(nome_menor,"tem",altura_menor,"por isso tem altura menor")

"""### 14. Um funcionário de uma empresa recebe, anualmente, aumento salarial.

**Sabe-se que:**

* Esse funcionário foi contratado em 2005, com salário inicial de R$ 1.000,00.
* Em 2006, ele recebeu aumento de 1,5% sobre seu salário inicial.
* A partir de 2007, os aumentos salariais sempre corresponderam ao dobro do percentual do ano anterior.

**Faça um programa que determine o salário atual desse funcionário.**

```
LEIA ano_atual

salario_inicial =1000
percentual_de_aumento_do_ano  = 1.5 / 100

aumento_do_ano = salario_inicial * percentual_de_aumento_do_ano
salario_do_ano = salario_inicial + aumento_do_ano

PARA ano NO INTERVALO DE 2007 ATÉ ano_atual + 1
    percentual_do_ano = percentual_do_ano * 2
    aumento_do_ano = salario_do_ano * percentual_do_ano
    salario_do_ano = salario_do_ano + aumento_do_ano
    
ESCREVA ano, salario_do_ano
```
"""

ano_atual = int(input("digite o ano atual:\n"))
ano_comeco = 2007
salario = 1000
percentual_de_aumento_por_ano = 1.5/100
percentual_de_aumento_por_ano2= 1.5/100

aumento_do_ano = salario * percentual_de_aumento_por_ano
salario_do_ano = salario + aumento_do_ano
while (ano_comeco < ano_atual):
  percentual_de_aumento_por_ano = percentual_de_aumento_por_ano * 2
  aumento_do_ano = salario_do_ano * percentual_de_aumento_por_ano
  salario_do_ano = salario_do_ano + aumento_do_ano
  ano_comeco ++1;
print(ano_comeco, salario_do_ano)
#for
ano_comeco = 2007
print("for")
aumento_do_ano2 = salario * percentual_de_aumento_por_ano2
salario_do_ano2 = salario + aumento_do_ano2
 for ano_comeco in range(ano_atual):
   percentual_de_aumento_por_ano2 = percentual_de_aumento_por_ano2 * 2
  aumento_do_ano2 = salario_do_ano2 * percentual_de_aumento_por_ano2
  salario_do_ano2 = salario_do_ano2 + aumento_do_ano2
  ano_comeco ++1;
print(ano_comeco, salario_do_ano)

"""### 15. Foi feita uma estatística em cinco cidades brasileiras para coletar dados sobre acidentes de trânsito. Foram obtidos os seguintes dados:

* nome da cidade;
* número de veículos de passeio;
* número de acidentes de trânsito com vítimas.

**Deseja-se saber:**

* o maior  índice de acidentes de trânsito e a que cidades pertence;
* o menor índice de acidentes de trânsito e a que cidades pertence;
* qual é a média de veículos nas cinco cidades juntas;
* qual é a média de acidentes de trânsito nas cidades com menos de 2.000 veículos de passeio.

#### ALGORITMO
---

```
total_de_cidades_pesquisadas = 5
somatoria_dos_veiculos_nas_cidades = 0
somatoria_dos_acidentes_nas_cidades_com_mais_de_2000_veiculos = 0
numero_de_cidades_com_mais_de_200_veiculos = 0

PARA cidade NO INTERVALO total_de_cidades_pesquisadas
    LEIA nome_da_cidade, numero_de_veiculos, numero_de_acidentes
    SE cidade == 0
        maior_casos_de_acidentes = numero_de_acidentes
        cidade_com_maior_casos_de_acidentes = nome_da_cidade
        menor_casos_de_acidentes = numero_de_acidentes
        cidade_com_maior_casos_de_acidentes = nome_da_cidade
    SENÃO
        SE numero_de_acidentes > maior_casos_de_acidentes
             maior_casos_de_acidentes = numero_de_acidentes
             cidade_com_maior_casos_de_acidentes = nome_da_cidade
        SE numero_de_acidentes < menor_casos_de_acidentes
            menor_caso_de_acidentes = numero_de_acidentes
            cidade_com_maior_casos_de_acidentes = nome_da_cidade
                
    somatoria_dos_veiculos_nas_cidades += numero_de_veiculos
    
    SE numero_de_veiculos > 2000
        soma_dos_acidentes_nas_cidades_acima_de_2000_veiculos += numero_de_acidentes
        numero_de_cidades_com_mais_de_200_veiculos += 1
        
media_de_carros_nas_cidades = somatoria_dos_veiculos_nas_cidades / total_de_cidades_pesquisadas

SE numero_de_cidades_com_mais_de_200_veiculos == 0
    ESCREVA “Não foi informada nenhuma cidade com menos de 2000 veículos”
SENAO
    media_de_acidentes_nas_cidade_com_mais_de_2000_veiculos = soma_dos_acidentes_nas_cidades_acima_de_2000_veiculos /                                                                  numero_de_cidades_com_mais_de_200_veiculos
    
    ESCREVA nome_da_cidade, cidade_com_maior_casos_de_acidentes
    ESCREVA nome_da_cidade, maior_casos_de_acidentes 
    ESCREVA media_de_carros_nas_cidades
    ESCREVA media_de_acidentes_nas_cidade_com_mais_de_2000_veiculos
```
"""

total_de_cidades_pesquisadas = 5
somatoria_dos_veiculos_nas_cidades = 0
somatoria_dos_acidentes_nas_cidades_com_mais_de_2000_veiculos = 0
numero_de_cidades_com_mais_de_200_veiculos = 0
 
while cidade < total_de_cidades_pesquisadas:
   
    nome_da_cidade = input("digite o nome da cidade:\n")
    numero_de_veiculos = int(input("digite o número de veiculos:\n"))
    numero_de_acidentes = int(input("digite o número de acidentes:\n"))
    if cidade == 0:
        maior_casos_de_acidentes = numero_de_acidentes
        cidade_com_maior_casos_de_acidentes = nome_da_cidade
        menor_casos_de_acidentes = numero_de_acidentes
        cidade_com_maior_casos_de_acidentes = nome_da_cidade
    else:
        if numero_de_acidentes > maior_casos_de_acidentes:
             maior_casos_de_acidentes = numero_de_acidentes
             cidade_com_maior_casos_de_acidentes = nome_da_cidade
        elif numero_de_acidentes < menor_casos_de_acidentes:
            menor_caso_de_acidentes = numero_de_acidentes
            cidade_com_maior_casos_de_acidentes = nome_da_cidade
 
    somatoria_dos_veiculos_nas_cidades += numero_de_veiculos
 
    if numero_de_veiculos > 2000:
        soma_dos_acidentes_nas_cidades_acima_de_2000_veiculos += numero_de_acidentes
        numero_de_cidades_com_mais_de_200_veiculos += 1
 
media_de_carros_nas_cidades = somatoria_dos_veiculos_nas_cidades / total_de_cidades_pesquisadas
 
if numero_de_cidades_com_mais_de_200_veiculos == 0
    ESCREVA “Não foi informada nenhuma cidade com menos de 2000 veículos”
else:
    media_de_acidentes_nas_cidade_com_mais_de_2000_veiculos = soma_dos_acidentes_nas_cidades_acima_de_2000_veiculos                                                                numero_de_cidades_com_mais_de_200_veiculos
 
    print(cidade_com_menor_casos_de_acidentes, "tem o maior número de acidentes",menor_casos_de_acidentes)
   
    print("media de carros nas cidadades:" ,media_de_carros_nas_cidades
    print("media de acidentes nas cidades com mais de 200 veiúclos:",media_de_acidentes_nas_cidade_com_mais_de_2000_veiculos)

"""### 16. Faça um programa que monte os oito primeiros termos da sequência de Fibonacci.

#### ALGORITMO
___
```
numero_de_elementos_da_sequencia = 8
elementoN = 0
elementoNmais1 = 1

ESCREVA elementoN
ESCREVA elementoNmais1

PARA elemento NO INTERVALO DE 3 ATÉ numero_de_elementos_da_sequencia
    valor_do_fibonacci_atual = elementoN + elementoNmais1
   
    ESCREVA valor_do_fibonacci_atual
    
    elementoN = elementoNmais1
    elementoNmais1 = valor_do_fibonacci_atual
    
```
"""

qtd_de_elementos_seq = 8
elementoN = 0;
elementoN_mais_um = 1
inicio = 0;
valor_fibonacci_atual = 0;
print("Sequência de fibonacci")
print("elemento:", elementoN)
print("elemento mais um:", elementoN_mais_um )
for inicio in range(qtd_de_elementos_seq):
    
   valor_fibonacci_atual = elementoN + elementoN_mais_um
   elementoN = elementoN_mais_um
   elementoN_mais_um = valor_fibonacci_atual

print("oitavo termo da sequência de fibonacci:", valor_fibonacci_atual )

print("elemento:", elementoN_mais_um )
print("elemento mais um:", valor_fibonacci_atual )
#while
prinnt("while")
while(inicio < qtd_de_elementos_seq):
   valor_fibonacci_atual = elementoN + elementoN_mais_um
   elementoN = elementoN_mais_um
   elementoN_mais_um = valor_fibonacci_atual

print("oitavo termo da sequência de fibonacci:", valor_fibonacci_atual )

"""### 17. Faça um programa que leia o número de termos, determine e mostre os valores de acordo com a série a seguir:

Série = 2, 7, 3, 4, 21, 12, 8, 63, 48, 16, 189, 192, 32, 567, 768...

####ALGORITMO
---
```
LEIA numero_de_termos

termo1 = 2
termo2 = 7
termo3 = 3

termo_atual = 4

ENQUANTO termo_atual <= numero_de_termos
    ESCREVA termo1, termo2, termo3
    
    termo1 = termo1 * 2
    ESCREVA termo1
    termo_atual += 1
    
    SE termo_atual <= numero_de_termos
        termo2 = termo2 * 3
        ESCREVA termo2
        termo_atual += 1
        
    SE termo_atual <= num_termos
        termo3 = termo3 * 4
        ESCREVA termo3
        termo_atual += 1
```
"""

numero_de_termos = int(input("digite o numero de termos:\n"))
 
termo1 = 2
termo2 = 7
termo3 = 3
 
termo_atual = 4
 
while termo_atual <= numero_de_termos:
    print(termo1, termo2, termo3)
 
    termo1 = termo1 * 2
    print(termo1)
    termo_atual += 1
 
    if termo_atual <= numero_de_termos:
        termo2 = termo2 * 3
        print(termo2)
        termo_atual += 1
 
    if termo_atual <= numero_de_termos:
        termo3 = termo3 * 4
        print(termo3)
        termo_atual += 1
#for
print("for")
for termo_atual in range(numero_de_termos):
    print(termo1, termo2, termo3)
 
    termo1 = termo1 * 2
    print(termo1)
    termo_atual += 1
 
    if termo_atual <= numero_de_termos:
        termo2 = termo2 * 3
        print(termo2)
        termo_atual += 1
 
    if termo_atual <= numero_de_termos:
        termo3 = termo3 * 4
        print(termo3)
        termo_atual += 1

"""### 18. Faça um programa que receba duas notas de seis alunos. Calcule e mostre:

* a média aritmética das duas notas de cada aluno; e
* a mensagem que está na tabela a seguir:


Média aritimética | Mesagem
---|---
Até 3|Reprovado
Entre 3 e 7 |Exame
De 7 para cima| Aprovado

* o total de alunos aprovados;
* o total de alunos de exame;
* o total de alunos reprovados;
* a média da classe.
"""

contador = 0;
aprovado = 0;
reprovado = 0;
exame = 0;

for contador in range(6):
   nota1 = float(input("digite a primeira nota do aluno numero:\n"))
   nota2 = float(input("digite a segunda nota do aluno numero:\n"))
   media = (nota1 + nota2)/2
   if media < 3:
      reprovado = reprovado + 1;
   elif media >= 3 and media < 7:
      exame = exame + 1
   else:
      aprovado = aprovado + 1;
print(aprovado,"alunos aprovados")
print(exame,"ficaram para exame")
print(reprovado,"alunos reprovados")
#while
print("while")
while(contador < 6):
   nota1 = float(input("digite a primeira nota do aluno numero:\n"))
   nota2 = float(input("digite a segunda nota do aluno numero:\n"))
   media = (nota1 + nota2)/2
   if media < 3:
      reprovado = reprovado + 1;
   elif media >= 3 and media < 7:
      exame = exame + 1
   else:
      aprovado = aprovado + 1;
print(aprovado,"alunos aprovados")
print(exame,"ficaram para exame")
print(reprovado,"alunos reprovados")

"""### 19. Em uma fábrica trabalham homens e mulheres divididos em três classes:

* trabalhadores que fazem até 30 peças por mês — classe 1;
* trabalhadores que fazem de 31 a 50 peças por mês — classe 2;
* trabalhadores que fazem mais de 50 peças por mês — classe 3.

** Os salários são compostos da sequinte maneira:**

* A classe 1 recebe salário mínimo.
* A classe 2 recebe salário mínimo mais 3% deste salário por peça, acima das 30 peças iniciais.
* A classe 3 recebe salário mínimo mais 5% desse salário por peça, acima das 30 peças iniciais.

** Faça um programa que receba:**

* o número do operário,
* o número de peças fabricadas no mês,
* o sexo do operário,

**Calcule e mostre:**

* o número do operário e seu salário;
* o total da folha de pagamento da fábrica;
* o número total de peças fabricadas no mês;
* a média de peças fabricadas pelos homens;
* a média de peças fabricadas pelas mulheres; e
* o número do operário ou operária de maior salário.

**A fábrica possui 15 operários.**

#### ALGORITMO
---
```
total_de_operarios = 15
valor_do_salario_minimo = 954

total_da_folha_de_pagamento_no_mes = 0
total_de_pecas_fabricadas_no_mes = 0

media_das_pecas_fabricados_por_homens = 0
media_das_pecas_fabricados_por_mulheres = 0

total_de_homens = 0
total_de_mulheres = 0

meta_minima = 30
meta_classe3 = 50

porcentagem_de_bonus_da_classe1 = 0
porcentagem_de_bonus_da_classe2 = 2 / 100
porcentagem_de_bonus_da_classe3 = 3 / 100

total_de_operarios_homens = 0
total_de_operarios_mulheres = 0

somatorio_das_pecas_fabricadas_por_homens = 0
somatorio_das_pecas_fabricadas_por_mulheres = 0

maior_salario_entre_os_operarios = -1

PARA operario NO INTERVALO de total_de_operarios
    ESCREVA “Digite o número do operário “
    LEIA numero_do_operario
    
    ESCREVA “Digite o sexo do operário (M ou F) “
    LEIA sexo_do_operario
    
    ESCREVA “Digite o total de peças fabricadas pelo operario“
    LEIA total_de_pecas_fabricadas_pelo_operario
    
    SE total_de_pecas_fabricadas_pelo_operario <= meta_minima
        porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe1
    SENAO SE total_de_pecas_do_operario >= meta_classe3
        porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe3
    SENAO
          porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe2
          
    SE ttotal_de_pecas_fabricadas_pelo_operario > meta_minima
        producao_acima_da_meta = total_de_pecas_fabricadas_pelo_operario - meta_minima
    SENAO
        producao_acima_da_meta = 0
    
    bonus_de_producao = valor_do_salario_minimo * porcentagem_da_classe_do_operario * producao_acima_da_meta
    
    salario_do_operario = valor_do_salario_minimo + bonus_de_producao
    
    ESCREVA numero_do_operario, salario_do_operario
    
    total_da_folha_de_pagamento_no_mes += salario_do_operario 
    total_de_pecas_fabricadas_no_mes += total_de_pecas_fabricadas_pelo_operario
    
    SE sexo_do_operario ESTA EM "Hh"
        total_de_homens += 1
        somatorio_das_pecas_fabricadas_por_homens += total_de_pecas_fabricadas_pelo_operario
        
    SE sexo_do_operario ESTA EM "Mm"
        total_de_mulheres += 1
        somatorio_das_pecas_fabricadas_por_mulheres += total_de_pecas_fabricadas_pelo_operario
        
    SE salario_do_operario > maior_salario_entre_os_operarios
        numero_do_operario_com_o_maior_salario = numero_do_operario
        maior_salario_entre_os_operarios = salario_do_operario
        
media_de_pecas_fabricadas_por_homens = somatorio_das_pecas_fabricadas_por_homens / total_de_homens

media_de_pecas_fabricada_por_mulheres = somatorio_das_pecas_fabricadas_por_mulheres / total_de_mulheres

IMPRIMA total_da_folha_de_pagamento_no_mes
IMPRIMA total_de_pecas_fabricadas_no_mes
IMPRIMA media_de_pecas_fabricada_por_homens
IMPRIMA media_de_pecas_fabricada_por_mulheres
IMPRIMA numero_do_operario_com_o_maior_salario
```
"""

total_de_operarios = 15
valor_do_salario_minimo = 954
 
total_da_folha_de_pagamento_no_mes = 0
total_de_pecas_fabricadas_no_mes = 0
 
media_das_pecas_fabricados_por_homens = 0
media_das_pecas_fabricados_por_mulheres = 0
 
total_de_homens = 0
total_de_mulheres = 0
 
meta_minima = 30
meta_classe3 = 50
 
porcentagem_de_bonus_da_classe1 = 0
porcentagem_de_bonus_da_classe2 = 2 / 100
porcentagem_de_bonus_da_classe3 = 3 / 100
 
total_de_operarios_homens = 0
total_de_operarios_mulheres = 0
 
somatorio_das_pecas_fabricadas_por_homens = 0
somatorio_das_pecas_fabricadas_por_mulheres = 0
 
maior_salario_entre_os_operarios = -1
 
for operario in range(total_de_operarios):
    
    numero_do_operario = int(input("digite o número de operario:\n"))
 
    
    sexo_do_operario = print("Digite o sexo do operário M ou F:")
 
    
    total_de_pecas_fabricadas_pelo_operario = int(input("digite o números de peças fabricadas pelo operario:\n"))
 
    if total_de_pecas_fabricadas_pelo_operario <= meta_minima:
        porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe1
    elif total_de_pecas_do_operario >= meta_classe3:
        porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe3
    else:
          porcentagem_da_classe_do_operario = porcentagem_de_bonus_da_classe2
 
    if ttotal_de_pecas_fabricadas_pelo_operario > meta_minima:
        producao_acima_da_meta = total_de_pecas_fabricadas_pelo_operario - meta_minima
    else:
        producao_acima_da_meta = 0
 
    bonus_de_producao = valor_do_salario_minimo * porcentagem_da_classe_do_operario * producao_acima_da_meta
 
    salario_do_operario = valor_do_salario_minimo + bonus_de_producao
 
    print("número de operario:",numero_do_operario,"salário do operario:",salario_do_operario)
 
    total_da_folha_de_pagamento_no_mes += salario_do_operario 
    total_de_pecas_fabricadas_no_mes += total_de_pecas_fabricadas_pelo_operario
 
    if sexo_do_operario == "M":
        total_de_homens += 1
        somatorio_das_pecas_fabricadas_por_homens += total_de_pecas_fabricadas_pelo_operario
 
    elif sexo_do_operario == "F":
        total_de_mulheres += 1
        somatorio_das_pecas_fabricadas_por_mulheres += total_de_pecas_fabricadas_pelo_operario
 
    if salario_do_operario > maior_salario_entre_os_operarios:
        numero_do_operario_com_o_maior_salario = numero_do_operario
        maior_salario_entre_os_operarios = salario_do_operario
 
media_de_pecas_fabricadas_por_homens = somatorio_das_pecas_fabricadas_por_homens / total_de_homens
 
media_de_pecas_fabricada_por_mulheres = somatorio_das_pecas_fabricadas_por_mulheres / total_de_mulheres
 
print("total de pagamento no mês",total_da_folha_de_pagamento_no_mes
print("total de peças fabricadas no mês:",total_de_pecas_fabricadas_no_mes)
print("media de peças fabricadas por homem:",media_de_pecas_fabricada_por_homens)
print("media de peças fabricadas por homem:",media_de_pecas_fabricada_por_mulheres)
print("numero de operario com maior salário:",numero_do_operario_com_o_maior_salario)

"""###  20. Foi feita uma pesquisa com as crianças de uma determinada localidade. Faça um programa que:

* leia o número de crianças nascidas no período;
* identifique o sexo (M ou F) e a idade da criança.

**O programa deve calcular e mostrar:**

* a percentagem de crianças do sexo marculino;
* a percentagem de crianças do sexo feminino;
* a percentagem de crianças menores que 24 meses.

**Observação:

porcentagem_de_meninos = total_de_meninos / total_de_criancas_nascidas * 100

porcentagem_de_meninas = total_de_meninas / total_de_criancas_nascidas * 100
porcentagem_de_criancas_menores_de_24_mese=criancas_menores_de_24_mese/total_de_criancas_nascidas*100
"""

numero_periodo = int(input("digite o número de crianças nascidas no periodo"))
i = 0
total_meninos = 0;
total_meninas = 0;
total_24 = 0;
while (i < numero_periodo):
  sexo = input("digite o sexo da criança sendo M OU F letrás maisculas:\n")
  idade = int(input("digite a idade de crianças por meses:\n"))
  if sexo == "M":
    total_meninos = total_meninos + 1
  elif sexo == "F":
    total_meninas = total_meninas + 1
  if idade < 24:
    total_24 = total_24 + 1;
  i = i + 1
  
  

porcentagem_de_meninos = total_meninos/ numero_periodo * 100
porcentagem_de_meninas = total_meninas/ numero_periodo * 100
procentagem_24 = total_24/numero_periodo * 100

print("porcentagem de meninos:", porcentagem_de_meninos)
print("porcentagem de meninas:",porcentagem_de_meninas)
print("porcentagem de serES humanos menores de 24 meses:",procentagem_24)

"""### 21.  Faça um programa que receba o valor de uma dívida e mostre uma tabela com os seguintes dados:

* valor da dívida,
* valor dos juros, 
* quantidade de parcelas
* valor da parcela.

**Os juros e a quantidade de parcelas seguem a tabela:** 

Quantidade de parcelas |  % de juros sobre o valor inicial da dívida
---|---
1 |0
3 |10
6 |15
9 |20
12 |25

**Exemplo de saída do programa:**

Valor da dívida|Valor dos juros (em reais) | Quantidade de parcelas| Valor da parcela
---|---|---|---
1.000,00 |0| 1| 1.000,00
1.100,00 |100 |3| 366,67
1.150,00 |150 |6| 191,67
"""

valor_inicial = float(input('Digite o valor_inicial da dívida: '))
juros = 0
num_parc = 1
total = valor_inicial
valor_parc = valor_inicial
print('Valor da dívida  \tValor dos juros (em reais)\tQuantidade de parcelas\tValor da parcela ')
print(total,'\t\t\t',juros,'\t\t\t\t',num_parc,'\t\t\t',valor_parc)
juros = 10
num_parc = 3
while juros <= 25:
    valor_juros = valor_inicial * juros / 100
    total = valor_inicial + valor_juros
    valor_parc = total / num_parc
    #print('Valor da dívida \tValor dos juros (em reais)\tQuantidade de parcelas\tValor da parcela ')
    print(total,'\t\t\t',juros,'\t\t\t\t',num_parc,'\t\t\t',valor_parc)
    num_parc = num_parc + 3
    juros = juros + 5

"""### 22. Faça um programa que receba:

* o preço unitário,
* a refrigeração (S para os produtos que necessitem de refrigeração e N para os que não necessitem)
* a categoria (A — alimentação; L — limpeza; e V — vestuário)

**Calcule e mostre:**

* O custo de estocagem, calculado de acordo com a tabela a seguir.


Preço unitário| Refrigeração| Categoria| Custo de estocagem
---|---|---|---
Até 20 | - |  A| 2,00
Até 20|-  |L  |3,00
Até 20| - |  V|4,00
----------------------|----------------------|----------------------|----------------------
Entre 20 e 50 (inclusive)|S  | - |6,00
Entre 20 e 50 (inclusive)|  N|  -| 0,00 |
----------------------|----------------------|----------------------|----------------------
Maior que 50| S| A |  5,00|
Maior que 50| S | L |  2,00| 
Maior que 50| S| V |  4,00| 
Maior que 50|  N|A ou V  |0,00  | 
Maior que 50|  N| L | 1,00 | 


* O imposto calculado de acordo com as regras a seguir:
  * Se o produto possuir **categoria A** e **refrigeração S**, seu imposto será de 2% sobre o preço
unitário; caso contrário, será de 4%.
  * O preço final, ou seja, preço unitário mais custo de estocagem mais imposto.
  * A classificação calculada usando a tabela a seguir.

Preço final| Classificação
---|---
Até 20,00 |Barato
Entre 20,00 e  100,00 (inclusive)|Normal
Acima de R$ 100,00| Caro

* A média dos valores adicionais, ou seja, a média dos custos de estocagem e dos impostos dos doze produtos.
* O maior preço final.
* O menor preço final.
* O total dos impostos.
* A quantidade de produtos com classificação barato.
* A quantidade de produtos com classificação caro.
* A quantidade de produtos com classificação normal.

####ALGORITMO
---

```
total_de_produtos = 12

total_de_produtos_baratos = 0
total_de_produtos_normais = 0
total_de_produtos_caros = 0

total_de_custos_adicionais = 0

PARA produto NO INTERVALO DE total_de_produtos
    LEIA preco_do_produto, produto_necessita_de_refrigeracao, categoria_do_produto
    
    SE preco_do_produto <= 20
        SE categoria_do_produto == "A"
            custo_de_estocagem = 2
        SE categoria_do_produto == "L"
            custo_de_estocagem = 3
        SE categoria_do_produto == "V"
            custo_de_estocagem = 4
           
    SE  prodo_do_produto > 20 E preco_do_produto <= 50
        SE produdo_necessida_de_refrigeracao == "S"
            custo_de_estocagem = 6
        SENAO
            custo_de_estocagem = 0
            
    SE preco_do_produto > 50
        SE produdo_necessida_de_refrigeracao == "S"
            SE categoria_do_produto == "A"
                custo_de_estocagem = 5
            SE categoria_do_produto == "L"
                custo_de_estocagem = 2
            SE categoria_do_produto == "V"
                custo_de_estocagem = 4
        SENAO
            SE categoria_do_produto = "A" OU categoria_do_produto = "V"
                custo_de_estocagem = 0
            SE cagegoria_do_produto = "L"
                custo_de_estocagem = 1
        
    SE categoria_sobre_o_produto == "A" e produdo_necessida_de_refrigeracao == "S"
        imposto_do_produto = 2 / 100
    SENAO
        imposto_sobre_o_produto = 4 / 100
    
    preco_final_sobre_produto = preco_do_produto + custo_de_estocagem_do_produto + imposto_sobre_o_produto
  
  ESCREVA custo_de_estocagem_do_produto, imposto_sobre_o_produto, preco_final_do_produto
  
  SE preco_final_sobre_produto <= 20
      total_de_produtos_baratos += 1
      classificacao_do_produto = "PRODUTO BARATO"
      
  SE preco_final_sobre_produto >  20 E preco_final_sobre_produto <=  20
      total_de_produtos_normais += 1
      classificacao_do_produto = "PRODUTO NORMAL"
      
  SE preco_final_sobre_produto >  100
      total_de_produtos_caros += 1
      classificacao_do_produto = "PRODUTO CARO"
      
  custo_adicional_do_produto = custo_de_estocagem_do_produto + imposto_sobre_o_produto
   
   total_de_custo_adicionais_de_todos_produtos += custo_adicional_do_produto
   total_de_impostos_de_todos_os_produtos += imposto_sobre_o_produto
   
   SE produto == 0
      preco_do_produto_mais_caro = preco_final_do_produto
      preco_do_produto_mais_barato = preco_final_do_produto
   SENAO
      SE preco_do_produto_mais_caro < preco_final_do_produto
          preco_do_produto_mais_caro = preco_final_do_produto
      SE preco_do_produto_mais_barato > preco_final_do_produto
          preco_do_produto_mais_barato = preco_final_do_produto
          
media_dos_valores_adicionais = total_de_custo_adicionaisl_de_todos_produtos / total_de_produtos

ESCREVA media_dos_valores_adicionais
ESCREVA preco_do_produto_mais_caro
ESCREVA preco_do_produto_mais_barato
ESCREVA total_de_produtos_baratos
ESCREVA total_de_produtos_normais
ESCREVA total_de_produtos_caros
   
```
"""

total_de_produtos = 12
 
total_de_produtos_baratos = 0
total_de_produtos_normais = 0
total_de_produtos_caros = 0
 
total_de_custos_adicionais = 0
 
for produto in range(total_de_produtos):
    preco_do_produto = float(input("digite o preço do produto:\n"))
    produto_necessita_de_refrigeracao = input("produto necessita de refrigeração sendo S para sim e N  para não:\n")
    categoria_do_produto = input("digite a categoria do produto sendo A para Alimentação e L para Limpeza e V para Vestuario:\n")
    
 
    if preco_do_produto <= 20:
        if categoria_do_produto == "A":
            custo_de_estocagem = 2
        elif categoria_do_produto == "L":
            custo_de_estocagem = 3
        elif categoria_do_produto == "V":
            custo_de_estocagem = 4
 
    elif prodo_do_produto > 20 E preco_do_produto <= 50:
        elif produdo_necessida_de_refrigeracao == "S"
            custo_de_estocagem = 6
        else:
            custo_de_estocagem = 0
 
    elif preco_do_produto > 50:
        if produdo_necessida_de_refrigeracao == "S":
            if categoria_do_produto == "A":
                custo_de_estocagem = 5
            elif categoria_do_produto == "L":
                custo_de_estocagem = 2
            elif categoria_do_produto == "V":
                custo_de_estocagem = 4
        else:
            if categoria_do_produto = "A" OU categoria_do_produto = "V":
                custo_de_estocagem = 0
            elif cagegoria_do_produto = "L":
                custo_de_estocagem = 1
 
    elif categoria_sobre_o_produto == "A" e produdo_necessida_de_refrigeracao == "S":
        imposto_do_produto = 2 / 100
    else:
        imposto_sobre_o_produto = 4 / 100
 
    preco_final_sobre_produto = preco_do_produto + custo_de_estocagem_do_produto + imposto_sobre_o_produto
 
  print("preço da estocagem do produto:",custo_de_estocagem_do_produto, ,"preço de imposto sobre o produto:",imposto_sobre_o_produto, "preço final do produto:",preco_final_do_produto)
 
  if preco_final_sobre_produto <= 20:
      total_de_produtos_baratos += 1
      classificacao_do_produto = "PRODUTO BARATO"
 
  elif preco_final_sobre_produto >  20 E preco_final_sobre_produto <=  20:
      total_de_produtos_normais += 1
      classificacao_do_produto = "PRODUTO NORMAL"
 
  elif preco_final_sobre_produto >  100:
      total_de_produtos_caros += 1
      classificacao_do_produto = "PRODUTO CARO"
 
  custo_adicional_do_produto = custo_de_estocagem_do_produto + imposto_sobre_o_produto
 
   total_de_custo_adicionais_de_todos_produtos += custo_adicional_do_produto
   total_de_impostos_de_todos_os_produtos += imposto_sobre_o_produto
 
   if produto == 0:
      preco_do_produto_mais_caro = preco_final_do_produto
      preco_do_produto_mais_barato = preco_final_do_produto
   else:
      if preco_do_produto_mais_caro < preco_final_do_produto:
          preco_do_produto_mais_caro = preco_final_do_produto
      if preco_do_produto_mais_barato > preco_final_do_produto:
          preco_do_produto_mais_barato = preco_final_do_produto
 
media_dos_valores_adicionais = total_de_custo_adicionaisl_de_todos_produtos / total_de_produtos
 
print("media dos valores nacionais:",media_dos_valores_adicionais)
print(" preco do produto mais caro:",preco_do_produto_mais_caro)
print(" preco do produto mais barato:",preco_do_produto_mais_barato)
print(" total de produto mais baratos:", total_de_produtos_baratos)
print(" total de produtos normais:", total_de_produtos_normais)
print(" total de produto mais caros:", total_de_produtos_caros)

"""### 23.Faça um programa que:

* leia um valor N inteiro e positivo
* Calcule e mostre o valor de E, conforme a fórmula:

E = $1 +\frac{1}{1!}+\frac{1}{2!}+\frac{1}{3!}+\frac{1}{4!}+ . . . +\frac{1}{N!}$
"""

termos = int(input('Digite um número '))
e = 1
for fat in range(1,termos+1):
    fatorial = 1  
    i=1
    while i <= fat:
        fatorial = fatorial * i 
        i = i + 1
    print('O fatorial de {} é {}.'.format(fat,fatorial))
    e = e + (1 / fatorial)
    print('E=',e)

"""###24.Faça um programa para calcular a tabuada do 2 até a do 9. USE DUAS ESTRUTURAS DE REPETIÇÃO"""

for x in range(2,10):
  for x2 in range(11):
    print( x,"x",x2,"=", x * x2)
    print("----------------------")

"""###25. Elabore um algoritmo que informada a idade de 10 nadadores o mesmo terá condições de classificar em uma das seguintes categorias: infantil = 5 - 10 anos; juvenil = 11-17 anos; adulto >= maiores de 18 anos. USE DUAS ESTRUTURAS DE REPETIÇÃO"""

x = 0;

soma = 0;
for x in range(10):
  idade = int(input("digite por favor a idade do nadador:\n"))
  if idade >=5 and idade <= 10:
    print("criança")
   
  elif idade  >= 11 and idade <= 17:
     
    print("juvenil")
  elif idade >= 18:
    print("adulto")
    
  else:
    print("invalido")