# -*- coding: utf-8 -*-
"""Keven Escovedo - 20201_P2_Alg_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ts7izJydm_kbLZ7imwzk72wQS_LT0iEl

###[3,00 pontos] **1.** Utilize a linguagem de programação PYTHON. Crie um programa que registre cinco pessoas. Delas leia sexo (m/f), peso e altura. Calcule e apresente os seguintes itens:
a) Quantos homens?

b) Quantas mulheres?

c) Média de alturas?

d) Quantas pessoas pesam menos de 30 kg?
"""

contador = 1;
qtd_mulheres = 0;
qtd_homens = 0;
soma_alturas = 0;
qtd_pesa_menos_30 = 0;

while contador <= 5:
     sexo = input("digite o sexo da pessoa sendo m(minusculo) para masculino e f(minusculo) para feminino:\n")
     peso = float(input("Digite o peso da pessoa em KG:\n"))
     altura = float(input("Digite a altura da pessoa em Metros:\n"))
     if sexo == "f":
         qtd_mulheres = qtd_mulheres + 1
     elif sexo == "m":
         qtd_homens = qtd_homens + 1
     soma_alturas = soma_alturas + altura
     if peso < 30:
         qtd_pesa_menos_30 = qtd_pesa_menos_30 + 1 
         
     contador = contador + 1;
print(" A quantidade de homens é de:",qtd_homens)
print(" A quantidade de mulheres é de:",qtd_mulheres)
print(" A média de alturas é de:", soma_alturas/5)
print(" A quantidade de pessoas que pesam menos 30 é de:",qtd_pesa_menos_30)

"""###[2,00 pontos] **2.** Utilize a linguagem de programação PYTHON. Crie um programa que leia um vetor de 10 elementos de nome de produtos e outro vetor de preços de produtos. Em outro laço de repetição, mostre o nome do produto e o preço do mesmo, mas o preço apresentado para alguns produtos será diferente, pois deve-se aplicar 5% de aumento aos produtos que estão entre os preços de 50 e 70 reais."""

produtos = []
precos = []
contador = 1;
index = 0;

while contador <= 10:
    produtos.append(input("Por favor digite o nome de um  produto:\n"))
    precos.append(float(input("Por favor digite o preço do produto:\n")))
                    
    contador = contador + 1;


while index <= 9:
     if precos[index] >= 50 and precos[index] <= 70:
        porcentagem = precos[index] * (5/100)
        aumento = precos[index] + porcentagem
        print("O preço de",produtos[index],"é de",aumento,"Reais")
       
     else:
        print("O preço de", produtos[index],"é de",precos[index],"Reais")
     index = index + 1