# -*- coding: utf-8 -*-
"""Keven Escovedo - 20201_Est_Dec_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIfqdId3Cb30jjaonejlUdSlbLgVC1F9

### 1. Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 300, reajuste de 50%; Salários maiores que 300, reajuste de 30%.
"""

try:
      #entrada de dados
      salario_funcionario = float(input("Por Favor digite o salário do funcionário em R$: "))
      #processamento/Saidas
      if(salario_funcionario <= 300):
          percentual_salario = salario_funcionario * 50/100
          salario_reanjado = salario_funcionario + percentual_salario
          print("O salário do Funcionário é R$:",salario_reanjado)
            
      else:
        percentual_salario = salario_funcionario * 30/100
        salario_reanjado = salario_funcionario + percentual_salario
        print("O salário do Funcionário é R$:",salario_reanjado)
        
  except:
         print("Valor inválido")

"""###2. Faça um algoritmo que leia o nome e a idade de uma pessoas, verifique se a idade de uma pessoa é menor ou maior de idade. Considera-se maior de idade uma pessoa com 18 anos ou mais. Como saída o algoritmo deve informar o nome e a idade da pessoa e depois uma mensagem se ela é ou não maior de idade."""

idade = 0;
  nome = input("Por favor o nome da pessoa: ")
  #processamento e entrada
  while idade < 1 or nota > 120:
    try:
        #entrada de dados
        idade = int(input("Por Favor digite a idade: "))
        #saida de dados
        if(idade >= 18):
           
           print(nome, "é maior de idade pois possui", idade, "de idade")
        else:
          print(nome, "é menor de idade pois possui", idade, "de idade")
        break
    except:
        print("Valor inválido")
        continue

"""###3. Tendo como dados de entrada a altura e o sexo (M/F) de uma pessoa (M-masculino ou F-feminino), construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
homem: (72.7 * altura) - 58;

mulher: (62.1 * altura) - 44.7
"""

peso = -1;
 sexo = "";

 
  #processamento e entrada
while sexo == "F" or sexo == "f" or sexo == 'M' or sexo == "m" or altura > 0 or altura <= 3 :
      try:
          #entrada de dados
          sexo = input("Por Favor digite o sexo do individuo M/F ou m/f sendo m para masculino e f para feminino: ")
          altura = float(input(" Por favor digite a altura metros:"))
          #saida de dados
          if(sexo == "M" or sexo =="m"):

            peso_ideal = (72.7 * altura) - 58
            print("O peso ideal para a pessoa de altura", altura, " metros do sexo mas masculino é de: " ,peso_ideal, "Kg")
          else:
            peso_ideal = (62.1 * altura) - 44.7
            print("O peso ideal para a pessoa de altura", altura, " metros do sexo mas feminino é de: ",peso_ideal, "Kg")
        

          break
      except:
          print("Valor inválido")
          continue

"""###4. Faça um algoritmo que leia um número inteiro e mostre uma mensagem indicando se este número é par ou ímpar e se é positivo ou negativo."""

numero_inteiro = 0;
 while numero_inteiro <= 0 or numero_inteiro >= 0:
    try:
        #entrada de dados
        numero_inteiro = int(input("Por Favor digite um numero inteiro: "))
        
        if(numero_inteiro % 2 == 0):
           
           print(numero_inteiro, "é par")
        else:
            print(numero_inteiro, "é impar")
        if(numero_inteiro < 0):
           
           print(numero_inteiro, "é negativo")
        elif(numero_inteiro > 0):
           print(numero_inteiro, "é positivo")
        else:
          print("numero neutro")
        break
    except:
        print("Valor inválido")
        continue

"""###5. Elabore um algoritmo que informando a idade de um nadador o mesmo terá condições de classificar em uma das seguintes categorias: 
infantil = 5 - 10 anos;
 
juvenil = 11-17 anos; 

adulto = maiores de 18 anos.
"""

idade = 1;
while numero_inteiro > 0 or numero_inteiro <= 120:
    try:
        #entrada de dados
        idade = int(input("Por Favor digite a idade do nadador: "))
        
        if(idade >= 5  and idade <= 10):
           
           print("O nadador é da categoria infantil.")
        elif(idade >= 11  and idade <= 17):
           
           print("O nadador é da categoria juvenil.")
        elif(idade >= 18):
           
           print("O nadador é da categoria adulto.")
        else:
          print("idade não adequada para praticar natação.")
         
        break
    except:
        print("Valor inválido")
        continue

"""###6. Um banco concederá um crédito especial aos seus clientes, variável com o saldo médio no último ano. Faça um algoritmo que leia o saldo médio de um cliente e calcule o valor do crédito de acordo com a tabela a seguir. Mostre uma mensagem informando o saldo médio e o valor do crédito.
        Saldo médio
        * de 0 a 200 nenhum crédito
        * de 201 a  400 20% do valor do saldo médio
        * de 401 a  600 30% do valor do saldo médio
        * acima de 601 40% do valor do saldo médio
"""

saldo_medio = 0;
while saldo_medio >= 0:
    try:
        #entrada de dados
        saldo_medio = float(input("Por Favor digite um saldo: "))
        
        if(saldo_medio >= 0 and saldo_medio <= 200):
           
           print("com o saldo de",saldo_medio,"você não possui credito")
        elif(saldo_medio >= 201  and saldo_medio <= 400):
           credito = saldo_medio  * (20/100)
           print("com o saldo de",saldo_medio,"você  possui credito de",credito)
        elif(saldo_medio >= 401  and saldo_medio <= 600):

         credito = saldo_medio  * (30/100)
         print("com o saldo de",saldo_medio,"você  possui credito de",credito)   
      
        else:
          credito = saldo_medio  * (40/100)
          print("com o saldo de",saldo_medio,"você  possui credito de",credito)
      
         
        break
    except:
        print("Valor inválido")
        continue

"""###7. A Organização Mundial de Saúde usa a seguinte tabela para determinar a condição de um adulto, para isso desenvolva um algoritmo para calcular o Índice de Massa Corporal (IMC) e apresenta-lo, dado pela fórmula: 
    IMC = peso / (altura)2   (o 2 elevado ao quadrado)

CONDIÇÃO |  IMC em adultos |
 ---|---
Abaixo do peso  |	Abaixo de 18.5  |
No peso normal	|	Entre 18.5 e 25|
Acima do peso	|	Entre 25.1 e 30|
Obeso		    |	Acima de 30|
"""

peso = 0;
altura = 0;
while massa >= 0 and altura >= 0:
    try:
        #entrada de dados
        peso = float(input("Por Favor digite o peso em kg: "))
        altura = float(input("Por Favor digite a altura em m: "))
        imc = peso/(pow(altura,2))

        if(imc < 18.5):
           
           print("O seu IMC é de", imc, "por isso você está abaixo do peso")
        elif(imc >= 18.5 and imc <= 25):
           print("O seu IMC é de", imc, "por isso você está no peso normal")
           
        elif(imc >= 25.1 and imc <= 30):
          print("O seu IMC é de", imc, "por isso você está acima do peso")

          
      
        else:
         print("O seu IMC é de", imc, "por isso você está obeso")
      
         
        break
    except:
        print("Valor inválido")
        continue

"""### 8. A nota final de um estudante é calculada a partir de três notas atribuídas, respectivamente, a um trabalho de laboratório, a uma avaliação semestral e a um exame final. A média das três notas mencionadas obedece aos pesos a seguir:

 NOTA |  PESO |
 ---|---
Trabalho de laboratório  |   2   |
Avaliação semestral      |   3   |
Exame final              |   5   |

### Faça um programa que receba as três notas, calcule e mostre a média ponderada e o conceito que segue a tabela

MÉDIA PONDERADA    | CONCEITO|
---|---
8,0 <= média <= 10  |    A 
7,0 <= média < 8,0  |    B 
6,0 <= média < 7,0  |    C 
5,0 <= média < 6,0  |    D 
 0,0 <= média < 5,0  |    E
       
media_ponderada = (nota_traballho * 2 + avaliacao_semestral * 3 + exame_final * 5) / 10
"""

while nota_trabalho >= 0 and nota_trabalho <= 10 and avaliaçao_semestral >= 0 and avaliaçao_semestral <= 10 and exame_final >= 0 and exame_final <= 10 :
    try:
        #entrada de dados
        nota_trabalho = float(input("Por Favor digite a nota do trabalho: "))
        avaliacao_semestral = float(input("Por favor digite a nota da avaliação semestral: "))
        exame_final = float(input("Por favor digite a nota do exame final: "))
        media = (nota_trabalho * 2 + avaliacao_semestral * 3 + exame_final * 5) / 10

       

        if(media >= 8 and media <= 10):
           
           print("A média ponderada foi de",media,"e o conceito é de A")
        elif(media >= 7 and media < 8):
           print("A média ponderada foi de",media,"e o conceito é de B")
           
        elif(media >= 6 and media < 7):
          print("A média ponderada foi de",media,"e o conceito é de C")
        elif(media >= 5 and media < 6):
          print("A média ponderada foi de",media,"e o conceito é de D")
        else:
          print("A média ponderada foi de",media,"e o conceito é de E")

          
      
    
      
         
        break
    except:
        print("Valor inválido")
        continue

"""### 9. Faça um programa que receba três notas de um aluno, calcule e mostre a média aritmética e a mensagem constante na tabela a seguir. Aos alunos que ficaram para exame, calcule e mostre a nota que deverão tirar para serem aprovados, considerando que a média exigida é 6,0.

MÉDIA ARITMÉTICA | MENSAGEM
    ---|---
    0,0 <= média < 3,0 |Reprovado
    3,0 <= média < 7,0|Exame
    7,0 <= média <= 10,0|Aprovado

```
SE media >= 3 E media < 7
    ESCREVA “Exame”
    nota_exame = 12 - media
    ESCREVA “Deve tirar nota”, nota_exame, “para ser aprovado”
"""

nota1 = 0
nota2=  0
nota3 = 0
while nota1 >= 0 and nota1 <= 10 and nota2 >= 0 and nota2 <= 10 and nota3 >= 0 and nota3 <= 10 :
    try:
        #entrada de dados
        nota1 = float(input("Por Favor digite a nota 1: "))
        nota2 = float(input("Por favor digite a nota 2: "))
        nota3 = float(input("Por favor digite a nota 3: "))
        media = (nota1 + nota2 + nota3) / 3

       

        if(media >= 7 and media <= 10):
            print("A média foi de",media,"e por isso o aluno foi aprovado") 
         
        elif(media >= 3 and media < 7):
           nota_exame = 12 - media
           print("A média  foi de",media,"e o aluno precisará fazer o exame, precisando tirar:",nota_exame)
           
       
        else:
          print("A média foi de",media,"e o por isso aluno reprovado")

          
      
    
      
         
        break
    except:
        print("Valor inválido")
        continue

"""### 10. Faça um programa que receba dois números e mostre o maior."""

numero1 = 0
numero2 = 0

while  numero1 >= 0 or numero1 < 0 and numero2 >= 0 or numero1 < 0:
    try:
        #entrada de dados
        numero1 = float(input("Por Favor digite o numero 1: "))
        numero2 = float(input("Por favor digite o numero 2 "))

       

        if(numero1 > numero2):
            print(numero1,"é maior que", numero2) 
         
        elif(numero1 < numero2):
            print(numero2,"é maior que", numero1) 
         
          
           
       
        else:
          print(numero2,"é igual que", numero1)   

          
      
    
      
         
        break
    except:
        print("Valor inválido")
        continue

"""### 11. Faça um programa que receba três números e mostre-os em ordem crescente. Suponha que o usuário digitará três números diferentes.

```
SE numero1 < numero2 E numero1 < numero3
    SE numero2 < numero3
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero2,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero1,“-”,num3,“-”,num2
SE numero2 < numero1 E numero2 < numero3
    SE numero1 < numero3
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero1,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero3,“-”,numero
SE numero3 < numero1 E numero3 < num2
    SE numero1 < numero2
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero1,“-”,numero2

    SE NÃO
     ESCREVA "A ordem crescente é:",“,numero3,“-”,numero2,“-”,numero1

```
"""

#entrada de dados
numero1 = float(input("Por Favor digite o numero 1: "))
numero2 = float(input("Por favor digite o numero 2 "))
numero3 = float(input("Por favor digite o numero 3 "))

          

if(numero1 < numero2 and numero1 < numero3):
    if(numero2 < numero3):
         print("A ordem crescente é:",numero1,"-",numero2,"-",numero3)
    else:
         print("A ordem crescente é:",numero1,"-",numero3,"-",numero2)
elif(numero3 < numero1 and numero3 < numero2):
    if(numero1 < numero2):
         print("A ordem crescente é:",numero3,"-",numero1,"-",numero2);
    else:
       print("A ordem crescente é:",numero3,"-",numero2,"-",numero1)
else:
    if(numero1 < numero3):
      print("A ordem crescente é:",numero2,"-",numero1,"-",numero3)
    else:
      print("A ordem crescente é: ",numero2,"-",numero3,"-",numero3)

"""### 12. Faça um programa que receba três números obrigatoriamente em ordem crescente e um quarto número que não siga essa regra. Mostre, em seguida, os quatro números em ordem decrescente. Suponha que o usuário digitará quatro números diferentes.

```code
SE numero4 > numero3
    ESCREVA “A ordem decrescente é: “,numero4,“-”,numero3,“-”,numero2,“-”,numero1
SE numero4 > numero2 E numero4 < numero3
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero4,“-”,numero2,“-”,numero1
SE numero4 > numero1 E numero4 < numero2
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero4, “-”,numero1
SE numero4 < numero1
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero1,“-”,numero4
```
"""

#entrada de dados
numero1 = float(input("Por Favor digite o numero 1: "))
numero2 = float(input("Por favor digite o numero 2 "))
numero3 = float(input("Por favor digite o numero 3 "))
numero4 = float(input("Por favor digite o numero 4 "))
if(numero4 > numero3):
    print("A ordem decrescente é:",numero4,"-",numero3,"-",numero2,"-",numero1)
elif(numero4 > numero2  and numero4 < numero3):
    print("A ordem decrescente é:",numero3,"-",numero4,"-",numero2,"-",numero1)
elif(numero4 > numero1 and numero4 < numero2):
    print("A ordem decrescente é:" ,numero3,"-",numero2,"-",numero4, "-",numero1)
else:
    print("A ordem decrescente é:",numero3,"-",numero2,"-",numero1,"-",numero4)



"""### 13. Faça um programa que receba quatro valores: I, A, B e C. Desses valores, I é inteiro e positivo, A, B e C são reais. Escreva os números A, B e C obedecendo à tabela a seguir.

*Suponha que o valor digitado para I seja sempre um valor válido, ou seja, 1, 2 ou 3, e que os números digitados sejam diferentes um do outro.*

  |VALOR DE I | FORMA A ESCREVER|
  |---|---|
  |1                  |A, B e C em ordem crescente.|
  |2                  |A, B e C em ordem decrescente|
  |3                  |O maior fica entre os outros dois números.|

  ```code
SE I == 1
    SE A<B E A<C
        SE B<C
            ESCREVA “A ordem crescente dos números é:”,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é:”,A,” -”,C,”-”,B
    SE B<A E B<C
        SE A<C
            ESCREVA “A ordem crescente dos números é:”,B,”-”,A,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,B,”-”,C,”-”,A
    SE C<A E C<B
        SE A<B
            ESCREVA “A ordem crescente dos números é: “,C,”-”,A,”-”,B
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,C,”-”,B,”-”,A
SE I == 2
    SE A>B E A>C
        SE B>C
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,C,”-”,B
    SE B>A E B>C
        SE A>C
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,A,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,C,”-”,A
    SE C>A E C>B
        SE A>B
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,A,”-”,B
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,B,”-”,A
SE I == 3
    SE A>B E A>C
        ESCREVA “A ordem desejada é: “,B,”-”,A,”-”,C
    SE B>A E B>C
        ESCREVA “A ordem desejada é: “,A,”-”,B,”-”,C
    SE C>A E C>B
        ESCREVA “A ordem desejada é: “,A,”-”,C,”-”,B
```
"""

I = float(input("Escreva os valores do I: "))
A = float(input("Escreva os valores do A: "))
B = float(input("Escreva os valores do B: "))
C = float(input("Escreva os valores do C: "))

if(I == 1):
    if(A < B and A < C):
        if(B < C):
            print("A ordem crescente dos números é:",A,"-",B,"-",C)
        else:
            print("A ordem crescente dos números é:",A,"-",C,"-",B)
    elif(B < A and B < C):
        if( A < C):
           print("A ordem crescente dos números é:",B,"-",A,"-",C)
        else:
           print("A ordem crescente dos números é:",B,"-",C,"-",A)
    elif(C < A and C < B):
        if(A < B):
           print("A ordem crescente dos números é:",C,"-",A,"-",B)
        else:
           print("A ordem crescente dos números é:",C,"-",B,"-",A)
elif(I == 2):
     if(A > B and A > C):
        if(B > C):
            print("A ordem decrescente dos números é:",A,"-",B,"-",C)
        else:
            print("A ordem decrescente dos números é:",A,"-",C,"-",B)
     elif(B > A and B > C):
        if(A > C):
            print("A ordem decrescente dos números é:",B,"-",A,"-",C)
        else:
            print("A ordem decrescente dos números é:",B,"-",C,"-",A)
     elif(C > A and C > B):
        if(A > B):
            print("A ordem decrescente dos números é:",C,"-",A,"-",B)
        else:
            print("A ordem decrescente dos números é:",C,"-",B,"-",A)
elif(I == 3):
    if(A > B and A > C):
       print("A ordem desejada é:",B,"-",A,"-",C)
    elif(B > A and B > C):
       print("A ordem desejada é:",A,"-",B,"-",C)
    else: 
      print("A ordem desejada é:",A,"-",C,"-",B)
else:
  print("Valor do I invalido")

"""### 14. Faça um programa que mostre o menu de opções a seguir, receba a opção do usuário e os dados necessários para executar cada operação.

    Menu de opções:
    1. Somar dois números.
    1. Raiz quadrada de um número.

    Digite a opção desejada:
  ```code
raiz = numero ** (1/2)
"""

numero1 = 0;
numero2 = 0;
opcao_desejada = 0;
while numero1 >= 0 or numero1 <= 0 and numero2 >= 0 or numero2 <= 0 and opcao_desejada == "1" or opcao_desejada == "2" :
    try:
        print("------------------------------------------------------------------")
        print("                       Menu de opções                             ")
        print("------------------------------------------------------------------")
        print("1. Soma de numeros")
        print("2.raiz de um numero")
      #entrada de dados
        opcao_desejada = input("Por Favor digite a opção desejada: ")
        

        if(opcao_desejada == "1"):
            numero1 = float(input("Por Favor digite um numero: "))
            numero2 = float(input("Por Favor digite um numero: "))  
            resultado = numero1 + numero2
            print("O resultado da soma é:",resultado)
            break
        if(opcao_desejada == "2"):
          numero1 = float(input("Por Favor digite um numero: "))
          resultado = numero1 ** (1/2)
          print("a raiz de",numero1, "é:",resultado)
         

         
          break
    except:
        print("Valor inválido")
        continue

"""### 15. Faça um programa que mostre a data e a hora do sistema nos seguintes formatos: DD/MM/AAAA – mês por extenso e hora:minuto.

Observação: ***from*** carrega um módulo/biblioteca da linguagem Python e o ***import*** é usado para informar qual objeto desta biblioteca queremos importar

    from datetime import datetime
    hoje = datetime.now()
    print (hoje.year)
    print (hoje.month)
    print (hoje.day)
    print (hoje.hour)
    print (hoje.minute)
    print (hoje.second)
"""

#processamento 
from datetime import datetime
hoje = datetime.now()
segundo = hoje.second
minuto = hoje.minute
hora = hoje.hour
dia = hoje.day
ano = hoje.year
mes = hoje.month
if( mes == 1):
	mes_exentenso = "Janeiro"
elif( mes == 2):
	mes_exentenso = "Fevereiro"
elif(mes == 3):
  mes_extenso = "Março"
elif(mes == 4):
  mes_extenso = "Abril"
elif(mes == 5):
  mes_extenso = "Maio"
elif(mes ==6):
  mes_extenso = "Junho"
elif(mes == 7):
  mes_extenso = "julho"
elif(mes == 8):
  mes_extenso = "Agosto"
elif(mes == 9):
  mes_extenso = "Setembro"
elif(mes == 10):
  mes_extenso = "Outubro"
elif(mes == 4):
  mes_extenso = "Novembro"
else:
  mes_exetenso ="Dezembro"
#saida de dados
print("Dia",dia,"do mês de",mes_extenso,"do ano de",ano,"sendo",hora,"hora(s) e",minuto,"minuto(s) e",segundo,"segundo(s).")

"""### 16. Faça um programa que determine a data cronologicamente maior entre duas datas fornecidas pelo usuário. Cada data deve ser composta por três valores inteiros, em que o primeiro representa o dia, o segundo, o mês e o terceiro, o ano.

  ```code
  SE ano1 > ano2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE ano2>ano1
      ESCREVA “A maior data é: “,dia2,”-”,mes2,”-”,ano2
  SENÃO SE mes1>mes2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE mes2>mes1
      ESCREVA “A maior data é: “,dia2, “-”,mes2,”-”,ano2
  SENÃO SE dia1>dia2
      ESCREVA “A maior data é: “-”,dia1,”-”,mia1,” -”,ano1
  SENÃO SE dia2>dia1
      ESCREVA “A maior data é: “,dia2,” -”,mes2,”-”,ano2
  SENÃO
      ESCREVA “As datas são iguais!”
  ```
"""

#entrada de dados.
print("Digite a data um sendo, o primeiro dia, depois mês e por ultimo ano")
dia1 = int(input("Digite o dia de 0-31:"))
mes1 = int(input("Digite o mes de 1-12:"))
ano1 = int(input("Digite o ano:"))
print("Digite a data outra data sendo, o primeiro dia, depois mês e por ultimo ano")
dia2 = int(input("Digite o dia de 0-31:"))
mes2 = int(input("Digite o mes de 1-12:"))
ano2 = int(input("Digite o ano:"))
if(ano1 > ano2):
    print("A maior data é:",dia1,"/",mes1,"/",ano1)
elif(ano2 > ano1):
    print("A maior data é:",dia2,"/",mes2,"/",ano2)
elif( mes1 > mes2):
    print("A maior data é:",dia1,"/",mes1,"/",ano1)
elif(mes2 > mes1):
    print("A maior data é:",dia2,"/",mes2,"/",ano2)
elif(dia1 > dia2):
      print("A maior data é:",dia1,"/",mes1,"/",ano1)
elif(dia2 > dia1):
      print("A maior data é:",dia2,"/",mes2,"/",ano2)
else:
      print("as datas são idênticas")

"""### 17. Faça um programa que receba a hora do início de um jogo e a hora do término (cada hora é composta por duas variáveis inteiras: hora e minuto). Calcule e mostre a duração do jogo (horas e minutos), sabendo que o tempo máximo de duração do jogo é de 24 horas e que ele pode começar em um dia e terminar no dia seguinte.
    SE min_inicial > min_f
        minuto_final = minuto_final + 60
        hora_final = hora_final – 1
    SE hora_inicial > hora_final
        hora_final = hora_final + 24
    minuto_duracao = minuto_final - minuto_inicial
    hora_duracao = hora_final - hora_inicial
"""

hora_inicial = int(input("Digite a hora inicial do jogo: "))
min_inicial = int(input("Digite o minuto em que o  jogo inicia: "))
hora_final = int(input("Digite a hora em que o jogo termina: "))
min_final = int(input("Digite o minuto em que o  jogo termina: "))
if(min_inicial > min_final):
    min_final = min_final + 60
    hora_final = hora_final - 1
if(hora_inicial > hora_final):
    hora_final = hora_final + 24
minuto_duracao = min_final - min_inicial
hora_duracao = hora_final - hora_inicial
print("o jogo dura:", hora_duracao,"horas e",minuto_duracao,"minutos")

"""### 18. Faça um programa que receba o código correspondente ao cargo de um funcionário e seu salário atual e mostre o cargo, o valor do aumento e seu novo salário. Os cargos estão na tabela a seguir.

  |CÓDIGO|CARGO|PERCENTUAL|
  |---|---|---|
  |1|Escriturário|50%|
  |2|Secretário|35%|
  |3|Caixa|20%|
  |4|Gerente|10%|
  |5|Diretor|Não tem aumento|

```code
SE cargo == 1
    ESCREVA “O cargo é Escriturário”
    aumento = salario * 50 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 2
    ESCREVA “O cargo é Secretário”
    aumento = salario * 35 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal]
SENÃO SE cargo == 3
    ESCREVA “O cargo é Caixa”
    aumento = salario * 20 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “,novo_sal
SENÃO SE cargo == 4
    ESCREVA “O cargo é Gerente”
    aumento = salario * 10 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 5
    ESCREVA “O cargo é Diretor”
    aumento = salario * 0 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
```
"""

print("---------------------------------------------PRograma que mostra o percentual de aumento--------------------------------------------------------------------------")
print("------------------------------------------------------------------------------------------------------------------------------------------------------------------")
print("codigo do cargo sendo:")
print("1-Escrituário")
print("2-secretário")
print("3-Caixa")
print("4-Gerente")
print("5-diretor")
print("------------------------------------------------------------------------------------------------------------------------------------------------------------------")
cargo = int(input("Digite o numero do codigo do cargo acima: "))
salario = float(input("Digite o salário do funcionário em R$: "))
if(cargo == 1):
    print("O cargo é Escriturário")
    aumento = salario * 50 / 100
    print("O valor do aumento é:", aumento)
    novo_sal = salario + aumento
    print("O novo salário é: ", novo_sal)
elif(cargo == 2):
    print("O cargo é Secretário")
    aumento = salario * 35 / 100
    print("O valor do aumento é:", aumento)
    novo_sal = salario + aumento
    print("O novo salário é:", novo_sal)
elif(cargo == 3):
    print("O cargo é Caixa")
    aumento = salario * 20 / 100
    print("O valor do aumento é:", aumento)
    novo_sal = salario + aumento
    print("O novo salário é: “,novo_sal")
elif(cargo == 4):
    print("O cargo é Gerente")
    aumento = salario * 10 / 100
    print("O valor do aumento é:", aumento)
    novo_sal = salario + aumento
    print("O novo salário é:", novo_sal)
else:
    print("O cargo é Diretor")
    aumento = salario * 0 / 100
    print("O valor do aumento é:", aumento,"Pois diretor não tem aumento")
    novo_sal = salario + aumento
    print("O novo salário é:", novo_sal)

"""### 19. Faça um programa que apresente o menu a seguir, permita ao usuário escolher a opção desejada, receba os dados necessários para executar a operação e mostre o resultado. Verifique a possibilidade de opção inválida e não se preocupe com restrições, como salário negativo.

    Menu de opções
    1. Imposto
    2. Novo salário
    3. Classificação
    Digite a opção desejada:

*Na opção 1: receber o salário de um funcionário, calcular e mostrar o valor do imposto usando as regras a seguir.*

  |SALÁRIO|PERCENTUAL DO IMPOSTO|
  |---|---|
  |Menor que  500,00|5%|
  |De  500,00 (inclusive) a  850,00 (inclusive)|10%|
  |Acima de  850,00|15%|

*Na opção 2: receber o salário de um funcionário, calcular e mostrar o valor do novo salário, usando as regras a seguir.*

  |SALÁRIO|AUMENTO|
  |---|---|
  |Maior que  1.500,00| 25,00|
  |De  750,00 (inclusive) a  1.500,00 (inclusive)| 50,00|
  |De  450,00 (inclusive) a  750,00| 75,00|
  |Menor que  450,00| 100,00|

*Na opção 3: receber o salário de um funcionário e mostrar sua classificação usando a tabela a seguir.*

|SALÁRIO|CLASSIFICAÇÃO|
|---|---|
|Até  700,00 (inclusive)|Mal remunerado|
|Maiores que  700,00|Bem remunerado|
"""

print("Menu de opções")
print("1-Imposto")
print("2-Novo Salário")
print("3-Classificação")
menu =int(input("Selecione o numero de uma das funções supracitadas:"))
salario = float(input("Digite o salário dos funcionários:"))
if(menu == 1):
  if(salario < 500):
    imposto = salario * 5/100
    print("Imposto em R$:",imposto)
  if(salario >= 500 and salario <= 850):
    imposto = salario * 10/100
    print("Imposto em R$:",imposto)
  else:
      imposto = salario * 15/100
      print("Imposto em R$:",imposto)
elif(menu == 2):
  if(salario > 1500):
    aumento = salario + 25
    print("Salario aumentado em R$:",aumento)
  if(salario >= 750 and salario <= 1500):
    aumento = salario + 50
    print("Salario aumentado em R$:",aumento)
  if(salario >= 450 and salario <= 750):
    aumento = salario + 75
    print("Salario aumentado em R$:",aumento)
  else:
     aumento = salario + 100
     print("Salario aumentado em R$:",aumento)  
else:
   if(salario <= 700):
     print("Mal remunerado")
   else:
    print("Bem remunerado")

"""###20. Faça um programa que receba o salário inicial de um funcionário, calcule e mostre o novo salário, acrescido de bonificação e de auxílio escola.

|SALÁRIO|BONIFICAÇÃO|
|---|---|
|Até  500,00|5% do salário|
|Entre  500,00 e 1.200,00|12% do salário|
|Acima de  1.200,00|Sem bonificação|
>
|SALÁRIO|AUXÍLIO ESCOLA|
|---|---|
|Até  600,00| 150,00|
|Acima de  600,00| 100,00|

novo_salario = salario + bonificacao + aux
"""

salario = float(input("Digite o salário dos funcionários:"))

if(salario < 500):
    bonificao = salario * 5/100
    
elif(salario >= 500 and salario <= 1200):
    bonificacao = salario * 12/100
    
else:
     bonificacao = 0
if(salario <= 600):
  auxilio = 150;
else:
  auxilio = 100
novo_salario = salario + bonificacao + auxilio
print("Novo salário em R$: ",novo_salario)

"""### 21. Faça um programa que receba o valor do salário mínimo, o número de horas trabalhadas, o número de dependentes do funcionário e a quantidade de horas extras trabalhadas. Calcule e mostre o salário a receber do funcionário de acordo com as regras a seguir:

  * O valor da hora trabalhada é igual a 1/5 do salário mínimo.
  * O salário do mês é igual ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
  * Para cada dependente, acrescentar  32,00.
  * Para cada hora extra trabalhada, calcular o valor da hora * trabalhada acrescida de 50%.
  * O salário bruto é igual ao salário do mês mais o valor dos dependentes mais o valor das horas extras.
  * Calcular o valor do impostoosto de renda retido na fonte de acordo com a tabela a seguir:

|IRFF|SALÁRIO BRUTO|
|---|---|
|Isento|Inferior a  200,00|
|10%|De  200,00 até 500,00|
|20%|Superior a  500,00|

  * O salário líquido é igual ao salário bruto menos IRRF.
  * A gratificação é de acordo com a tabela a seguir:

|SALÁRIO LÍQUIDO|GRATIFICAÇÃO|
|---|---|
|Até 350,00| 100,00|
|Superior a  350| 50,00|

  * O salário a receber do funcionário é igual ao salário líquido mais a gratificação.

  ```code
  LEIA salario_minimo, numero_de_horas_trabalhadas, numero_de_dependentes, numero_de_horas_extras
  
  valor_da_hora = 1/5 * salario_minimo
 salario_do_mes = numero_de_horas_trabalhadas * valor_da_hora
  valor_dos_dependentes = 32 * numero_de_dependentes
  valor_da_hora_extra = numero_de_horas_extras * (valor_da_hora + (valor_da_hora * 50/100))
  salario_bruto =salario_do_mes + valor_dos_dependentes + valor_da_hora_extra
  
  SE salario_bruto < 200
        ENTÃO imposto = 0
  SE salario_bruto >= 200 E salario_bruto <= 500
        ENTÃO imposto = salario_bruto * 10/100
  SE salario_bruto > 500
       ENTÃO imposto = salario_bruto * 20/100
  salario_liquido = salario_bruto – imposto
  SE salario_liquido <= 350
        ENTÃO gratificacao = 100
  SE salario_liquido > 350
        ENTÃO gratificacao = 50
  salario_a_receber = salario_liquido + gratificacao
  
  ESCREVA salario_a_receber
  ```
"""

salario_minimo = float(input("Digite o salário minimo em R$: "))
numero_de_horas_trabalhadas = int(input("Digite o numero de horas trabalhadas: "))
numero_de_dependentes = int(input("Digite o número de depedentes: ")) 
numero_de_horas_extras = int(input("Digite o numero de horas extras: "))
 
valor_da_hora = 0.2 * salario_minimo
salario_do_mes = numero_de_horas_trabalhadas * valor_da_hora
valor_dos_dependentes = 32 * numero_de_dependentes
valor_da_hora_extra = numero_de_horas_extras * (valor_da_hora + (valor_da_hora * 50/100))
salario_bruto =salario_do_mes + valor_dos_dependentes + valor_da_hora_extra
 
if(salario_bruto < 200):
    imposto = 0
elif(salario_bruto >= 200 and salario_bruto <= 500):
    imposto = salario_bruto * 10/100
elif(salario_bruto > 500):
    imposto = salario_bruto * 20/100
    salario_liquido = salario_bruto - imposto
elif(salario_liquido <= 350):
    gratificacao = 100
elif(salario_liquido > 350):
    gratificacao = 50
salario_a_receber = salario_liquido + gratificacao
 
print("O salário a receber em R$:",salario_a_receber)

"""### 22 Um supermercado deseja reajustar os preços de seus produtos usando o seguinte critério: o produto poderá ter seu preço aumentado ou diminuído. Para o preço ser alterado, o produto deve preencher pelo menos um dos requisitos a seguir:

|VENDA MÉDIA MENSAL|PREÇO ATUAL|% DE AUMENTO|% DE DIMINUIÇÃO|
|---|--|---|---|
|< 500|<  30.000|10|-|
|\>= 500 e <1.200|\>=  30,00 e <  80,00|15|-|
|\>= 1,200|\>=  80,00|-|20|

* Faça um programa que receba o preço atual e a venda média mensal do produto, calcule e mostre o novo preço.

```code
LEIA preco_atual, media_mensal_de_vendas

SE media_mensal_de_vendas < 500 OU preco_atual < 30
    novo_preco = preco_atual + 10/100 * preco_atual
SENÃO SE media_mensal_de_vendas >= 500 E media_mensal_de_vendas < 1200 OU preco_atual >= 30 E preco_atual<80
    ENTÃO novo_preco = preco_atual + 15 / 100 * preco_atual
SENÃO SE venda >= 1200 OU preco_atual >= 80
    ENTÃO novo_preco = preco_atual – 20 / 100 * preco_atual
      
ESCREVA novo_preco
```
"""

preco_atual = float(input("Digite o preço atual: "))
media_mensal_de_vendas = int(input("Digite a media de vendas:"))
 
if(media_mensal_de_vendas < 500 or preco_atual < 30):
    novo_preco = preco_atual + 10/100 * preco_atual
elif(media_mensal_de_vendas >= 500 and media_mensal_de_vendas < 1200 or preco_atual >= 30 and preco_atual<80):
     novo_preco = preco_atual + 15 / 100 * preco_atual
else:
    novo_preco = preco_atual - 20 / 100 * preco_atual
print("Novo Preço:",novo_preco)

"""### 23. Faça um programa para resolver equações do 2 o grau.

**ax² + bx + c = 0**

A variável *a* deve ser diferente de zero*

  * delta = b ** 2 - 4 * a * c
  * delta < 0.  **Não existe raiz real**
  * delta = 0. **Existe uma raiz real**
    * x = (-b) / (2 * a)
  * delta > 0. **Existem duas raízes reais**
    * x1 = (-b + delta )/ (2 * a)
    * x2 = (-b - delta )/ (2 * a)

```code
LEIA a, b, c
SE a = 0
    ESCREVA “Estes valores não formam uma equação de segundo grau” 
SENÃO
    delta = (b * b) – ( 4 * a * c)
    SE delta < 0
        ENTÃO ESCREVA “Não existe raiz real”
    SE delta = 0
        ESCREVA “Existe uma raiz real”
        x1 = (– b) / (2 * a)
        ESCREVA x1
    SE delta > 0
        ESCREVA “Existem duas raízes reais”
        x1 = (– b) + raiz(delta) / (2 * a)
        x2 = (– b) - raiz(delta) / (2 * a)
        ESCREVA(x1, x2)
```
"""

a = int(input("Digite o Valor de a: "))
b = int(input("Digite o Valor de b: "))
c = int(input("Digite o Valor de c: "))
if(a == 0):
    print("Estes valores não formam uma equação de segundo grau") 
else:
    delta = (b * b) - ( 4 * a * c)
    if(delta < 0):
        print("Não existe valor real")
    elif(delta == 0):
        print("Existe uma raiz real")
        x1 = (-b) / (2 * a)
        print("x1:",x1)
    else:
        print("existe duas raizes reais")
        import math
        x1 = (-b) + math.sqrt(delta) / (2 * a)
        x2 = (-b) - math.sqrt(delta) / (2 * a)
        print("x1:",x1)
        print("x2:",x2)

"""### 24. Dados três valores X, Y e Z, verifique se eles podem ser os comprimentos dos lados de um triângulo e, se forem, verifique se é um triângulo equilátero, isósceles ou escaleno. Se eles não formarem um triângulo, escreva uma mensagem.
Considere que:
* o comprimento de cada lado de um triângulo é menor que a soma dos outros dois lados;
* chama-se equilátero o triângulo que tem três lados iguais;
* denomina-se isósceles o triângulo que tem o comprimento de dois lados iguais;
* recebe o nome de escaleno o triângulo que tem os três lados diferentes.

```code
LEIA x, y, z
SE x < y + z E y < x + z E z < x + y
    SE x = y E y = z
        ESCREVA “Triângulo Equilátero”
    SENÃO SE x = y OU x = z OU y = z
        ENTÃO ESCREVA “Triângulo Isósceles”
    SENÃO SE x ≠ y E x ≠ z E y ≠ z
        ENTÃO ESCREVA “Triângulo Escaleno”
SENÃO
    ESCREVA “Essas medidas não formam um triângulo”
```
"""

x = float(input("Digite o valor do lado x do triângulo: ")) 
 y = float(input("Digite o valor do lado y do triângulo: ")) 

 z = float(input("Digite o valor do lado z do triângulo: ")) 
if(x < y + z and y < x + z and z < x + y):
    if(x == y and y == z):
        print("Triângulo Equilátero")
    elif(x == y or x == z or y == z):
        print("Triângulo Isósceles")
    elif(x != y and x != z and y != z):
        print("Triângulo Escaleno")
else:
    print("Os lados não formam um triângulo")

"""### 25. Faça um programa que receba a altura e peso de uma pessoa. De acordo com a tabela a seguir, verifique e mostre a classificação dessa pessoa.

|ALTURA|ATÉ 60|ENTRE 60 E 90 (INCLUSIVE)|ACIMA DE 90|
|---|---|---|---|
|Menores que 1,20|A|D|G|
|De 1,20 a 1,70|B|E|H|
|Maiores que 1,70|C|F|I|

```code
LEIA altura, peso
SE altura < 1.20
    SE peso <= 60
        ENTÃO ESCREVA “A”
    SE peso > 60 E peso <= 90
        ENTÃO ESCREVA “D”
    SE peso > 90
        ENTÃO ESCREVA “G”
SE altura >= 1.20 E altura <= 1.70
    SE peso <= 60
        ESCREVA “B”
    SE peso > 60 E peso <= 90
        ESCREVA “E”
    SE peso > 90
        ESCREVA “H”
SE altura > 1.70
    SE peso <= 60
        ESCREVA “C”
    SE peso > 60 E peso <= 90
        EESCREVA “F”
    SE peso > 90
        ESCREVA “I”
```
"""

altura = float(input("Digite a altura da pessoa: "))
peso = float(input("Digite o peso da pessoa: "))
if(altura < 1.20):
    if(peso <= 60):
        print("A")
    elif(peso > 60 and peso <= 90):
        print("D")
    else:
        print("G")
elif(altura >= 1.20 and altura <= 1.70):
    if(peso <= 60):
        print("B")
    elif(peso > 60 and peso <= 90):
        print("E")
    else:
        print("H")
else:
    if(peso <= 60):
        print("C")
    elif(peso > 60 and peso <= 90):
        print("F")
    else:  
        print("I")

"""### 26. Faça um programa que receba:

* O código de um produto comprado, supondo que a digitação do código do produto seja sempre válida, isto é, um número * inteiro entre 1 e 10.
* O peso do produto em quilos.
* O código do país de origem, supondo que a digitação do  código seja sempre válida, isto é, um número inteiro entre 1 e 3.

|CÓDIGO DO PAÍS DE ORIGEM|IMPOSTO|
|---|---|
|1|0%|
|2|15%|
|3|25%|

|CÓDIGO DO PAÍS DO PRODUTO|IMPOSTO|
|---|---|
|1 a 4|10|
|5 a 7|25|
|8 a 10|35|

Calcule e mostre:
* o peso do produto convertido em gramas;
* o preço total do produto comprado;
* valor do imposto, sabendo que ele é cobrado sobre o * preço total do produto comprado e dependendo país de origem;
* o valor total, preço total do produto mais imposto.

```code
LEIA codigo_do_produto, peso_quilos, codigo_do_paiz
peso_em_gramas = peso_quilos * 1000
ESCREVA peso_em_gramas
SE codigo_do_produto >= 1 E codigo_do_produto <= 4
   preco_por_grama = 10
SE codigo_do_produto >= 5 E codigo_do_produto <= 7
   preco_por_grama = 25
SE codigo_do_produto >= 8 E codigo_do_produto <= 10
   preco_por_grama = 35    
preco_total = peso_em_gramas *preco_por_grama
ESCREVA preco_total
SE codigo_do_paiz = 1
    imposto = 0
SE codigo_do_paiz = 2
    imposto = preco_total * 15/100
SE codigo_do_paiz = 3
    imposto = preco_total * 25/100    
ESCREVA imposto
valor_total = preco_total + imposto
ESCREVA valor_total
```
"""

codigo_do_produto = int(input("Indique o codigo do pais onde é vendido o produto: "))
peso_quilos = float(input("Digite o peso em quilos do produto: "))
codigo_do_pais = int(input("Digite o codigo do pais de origem do produto: "))
peso_em_gramas = peso_quilos * 1000
print("peso em gramas",peso_em_gramas)
if(codigo_do_produto >= 1 and codigo_do_produto <= 4):
   preco_por_grama = 10
elif(codigo_do_produto >= 5 and codigo_do_produto <= 7):
   preco_por_grama = 25
else:
   preco_por_grama = 35    
preco_total = peso_em_gramas *preco_por_grama
print("Preço total em R$:",preco_total)
if(codigo_do_pais == 1):
    imposto = 0
elif(codigo_do_pais == 2):
    imposto = preco_total * 15/100
elif(codigo_do_pais == 3):
    imposto = preco_total * 25/100
else: 
  print("Codigo de pais de origem invalido")
print("Imposto em R$:",imposto)
valor_total = preco_total + imposto
print("Valor total em R$:",valor_total)

"""### 27. Faça um programa que receba:
* o código do estado de origem da carga de um caminhão, supondo que a digitação do código do estado seja sempre válida, isto é, um número inteiro entre 1 e 5;
* o peso da carga do caminhão em toneladas;
* o código da carga, supondo que a digitação do código seja sempre válida, isto é, um número inteiro entre 10 e 40.

| CÓDIGO DO ESTADO| IMPOSTO|
|---|---|
|1|35%|
|2|25%|
|3|15%|
|4|5%|
|5|Isento|
>
CÓDIGO DA CARGA|PREÇO POR QUILO
---|---
10 a 20|100
21 a 30|250
31 a 40|400

Calcule e mostre:
* o peso da carga do caminhão convertido em quilos;
* o preço da carga do caminhão;
* o valor do imposto, sabendo que o imposto é cobrado sobre o preço da carga do caminhão e depende do estado de origem;
* o valor total transportado pelo caminhão, preço da carga mais imposto.

```
LEIA codigo_do_estado, peso_em_toneladas, codigo_da_carga
peso_em_quilos = peso_em_toneladas * 1000
ESCREVA peso_em_quilos
SE cod_carga >= 10 E cod_carga <= 20
    preco_da_carga = 100 * peso_em_quilos
SE cod_carga >= 21 E cod_carga <= 30
    preco_da_carga = 250 * peso_em_quilos
SE cod_carga >= 31 E cod_carga <= 40
    preco_da_carga = 340 * peso_em_quilos   
ESCREVA preco_da_carga
SE codigo_do_estado = 1
    imposto = 35/100 * preco_da_carga
SE cod_est = 2
    imposto = 25/100 * preco_da_carga
SE cod_est = 3
    imposto = 15/100 * preco_ds_carga
SE cod_est = 4
    imposto = 5/100 * preco_da_carga
SE cod_est = 5
    imposto = 0
ESCREVA imposto
valor_total = preco_da_carga + imposto
ESCREVA valor_total
```
"""

codigo_estado =  int(input("Escreva o codigo do estado da carga: "))
peso_em_toneladas = float(input("Escreva o peso em toneladas da carga: "))
codigo_carga =   int(input("Escreva o codigo  da carga: "))
peso_em_quilos = peso_em_toneladas * 1000
print("Peso em quilos:",peso_em_quilos)
if(codigo_carga >= 10 and codigo_carga <= 20):
    preco_da_carga = 100 * peso_em_quilos
elif(codigo_carga >= 21 and codigo_carga <= 30):
    preco_da_carga = 250 * peso_em_quilos
else:
    preco_da_carga = 340 * peso_em_quilos   
print("O preço da carga:",preco_da_carga)
if(codigo_do_estado == 1):
    imposto = 35/100 * preco_da_carga
elif(codigo_estado == 2):
    imposto = 25/100 * preco_da_carga
elif(codigo_estado == 3):
    imposto = 15/100 * preco_ds_carga
elif(codigo_estado == 4):
    imposto = 5/100 * preco_da_carga
elif(cod_estado == 5):
    imposto = 0
else:
    print("Valor invalido")
print("Escreva o valor do imposto:", imposto)
valor_total = preco_da_carga + imposto
print("Escreva o valor total:",valor_total)

"""### 28. Faça um programa que receba o salário base e o tempo de serviço de um funcionário. Calcule e mostre:
* O imposto, conforme a tabela a seguir.
* A gratificação, de acordo com a tabela a seguir.
* O salário líquido, ou seja, salário base menos imposto mais gratificação.
* A categoria, que está na tabela a seguir.

```
LEIA salario_base, tempo

SE salario_base < 200
    imposto = 0
SENÃO SE salario_base <= 450
    imposto = 3/100 * salario_base
SENÃO SE sal_base < 700
    imposto = 8/100 * salario_base
SENÃO
    imposto = 12/100 * salario_base
ESCREVA imposto
SE salario_base > 500
    SE tempo <= 3
         gratificacao = 20
    SENÃO 
        gratificacao = 30
SENÃO
    SE tempo <= 3
        gratificacao = 23
    SENÃO SE tempo < 6
        gratificacao = 35
    SENÃO gratificacao = 33
ESCREVA gratificacao
salario_liquido = salario_base – imposto + gratificacao
ESCREVA salario_liqquido
SE salario_liquido <= 350
    ESCREVA “Classificação A”
SENÃO
    SE salario_liqquido < 600
        ESCREVA “Classificação B”
    SENÃO
        ESCREVA “Classificação C”
```
"""

salario_base = float(input("Digite o salário base em R$: "))
tempo = int(input("Digite o tempo de serviço funcionário em ano: "))
 
if(salario_base < 200):
    imposto = 0
elif(salario_base <= 450):
    imposto = 3/100 * salario_base
elif(salario_base < 700):
    imposto = 8/100 * salario_base
else:
    imposto = 12/100 * salario_base
    print("Imposto: ",imposto)
if(salario_base > 500):
    if(tempo <= 3):
         gratificacao = 20
    else: 
        gratificacao = 30
else:
    if(tempo <= 3):
        gratificacao = 23
    elif(tempo < 6):
        gratificacao = 35
    else:
       gratificacao = 33
    print("Gratificação:",gratificacao)
salario_liquido = salario_base - imposto + gratificacao
print("Salário Liquido:",salario_liquido)
if( salario_liquido <= 350):
   print("Classificação A:")
else:
    if(salario_liquido < 600):
        print("Classificação B")
    else:
        print("Classificação B")

"""### 29. Faça um programa que:
* receba o valor do salário mínimo,
* o turno de trabalho (M — matutino; V — vespertino; ou N — noturno),
* a categoria (O — operário; G — gerente) 
* número de horas trabalhadas no mês de um funcionário. 

*Suponha a digitação apenas de dados válidos e, quando houver digitação de letras, utilize maiúsculas.*

**Calcule e mostre:**

* O coeficiente do salário, de acordo com a tabela a seguir.

TURNO DE TRABALHO|VALOR DO COEFICIENTE
---|---
M - Matutino|10% do salário mínimo
V - Vespertino|15% do salário mínimo
N - Noturno|20% do salário mínimo

* O valor do salário bruto, ou seja, o número de horas trabalhadas multiplicado pelo valor do coeficiente do salário.

* O imposto, de acordo com a tabela a seguir.

CATEGORIA| SALÁRIO BRUTO|IMPOSTO SOBRE O SALÁRIO BRUTO
---|---|---
O - Operário|>= 300,00|5%
O - Operário|< 300,00|3%
G - Gerente|>= 300,00|6%
G - Gerente|< 300,00|4%

* A gratificação, de acordo com as regras a seguir. Se o funcionário preencher todos os requisitos a seguir, sua gratificação será de 50,00; caso contrário, será de 30,00. Os requisitos são:
 * Turno: Noturno
  * Número de horas trabalhadas: Superior a 80 horas
  * O auxílio alimentação, de acordo com as seguintes regras.
* Auxilio alimentação, um terço do seu salário bruto; caso contrário, será de metade do seu salário bruto. Os requisitos são:
  * Se o funcionário preencher algum dos requisitos a seguir, seu auxílio alimentação será de 
  * Categoria: Operário
  * Coeficiente do salário: < = 25
* O salário líquido, ou seja, salário bruto menos imposto mais gratificação mais auxílio alimentação.
* A classificação, de acordo com a tabela a seguir:

SALÁRIO LÍQUIDO|MENSAGEM
---|---
Menor que 350,00|Mal remunerado
Entre 350 e 600,00|Normal
Maior que 600,00|Bem remunerado

```
LEIA salario_minino, turno, categoria, numero_de_horas_trabalhadas
SE turno = “M”
     coeficiente = 10/100 * salario_minino
SE turno = “V”
     coeficiente = 15/100 * salario_minino
SE turno = “N”
     coeficiente = 12/100 * salario_minino
     
ESCREVA coeficiente

salario_bruto = numero_de_horas_trabalhadas * coeficiente

ESCREVA salario_bruto

SE categoria = “O”
    SE sal_bruto >= 300
        imposto = 5/100 * sal_bruto
    SENÃO
        imposto = 3/100 * sal_bruto
SENÃO
    SE salario_bruto >= 400
        imposto = 6/100 * salario_bruto
    SENÃO
         imposto = 4/100 * salario_bruto
         
ESCREVA imposto

SE turno = “N” E numero_de_horas_trabalhadas > 80
    gratificacao = 50
SENÃO
    gratificacao = 30
    
ESCREVA gratificacao

SE categoria = “O” OU coeficiente <= 25
    auxilio = 1/3 * salario_bruto
SENÃO
    auxilio = 1/2 * salario_bruto
    
ESCREVA auxilio

salario_liquido = salario_bruto – imposto + gratificacao + auxilio

ESCREVA salario_liquido

SE salario_liquido < 350
     ESCREVA “Mal Remunerado”
SE salario_liquido >= 350 E salario_liqquido <= 600
     ESCREVA “Normal”
SE salario_liquido > 600
     ESCREVA “Bem Remunerado”
```
"""

salario_minino = float(input("Digite o salário minimo de funcionário: "))
turno = input("Digite o turno sendo M para matino, Vespertino para tarde, N para noturno: ") 
categoria = input("Escreva a categoira sendo O-operário e G-gerente")
numero_de_horas_trabalhadas = int(input("Digite o números de horas trabalhadas: "))
if(turno == "M" or turno == "m"):
     coeficiente = 10/100 * salario_minino
elif(turno == "V" or turno == "v"):
     coeficiente = 15/100 * salario_minino
else:
     coeficiente = 12/100 * salario_minino
 
print("Coeficiente:",coeficiente)
 
salario_bruto = numero_de_horas_trabalhadas * coeficiente
 
print("Salário bruto em R$:",salario_bruto)
 
if(categoria == "O" or categoria == "o"):
    if(sal_bruto >= 300):
        imposto = 5/100 * sal_bruto
    else:
        imposto = 3/100 * sal_bruto
else:
    if(salario_bruto >= 400):
        imposto = 6/100 * salario_bruto
    else:
         imposto = 4/100 * salario_bruto
 
print("Imposto em R$",imposto)
if(turno == "N" or turno == "n" and numero_de_horas_trabalhadas > 80):
    gratificacao = 50
else:
    gratificacao = 30

print("Gratificação em R$:",gratificacao)
 
if(categoria == "O" or categoria == "o" or coeficiente <= 25):
    auxilio = 1/3 * salario_bruto
else:
    auxilio = 1/2 * salario_bruto
 
print("Auxilio em R$:",auxilio)
 
salario_liquido = salario_bruto - imposto + gratificacao + auxilio
 
print("Salário liquido em R$:",salario_liquido)
 
if(salario_liquido < 350):
     print("Mal Remunerado")
if(salario_liquido >= 350 and salario_liquido <= 600):
     print("Nomral")
else:
     print("Bem Remunerado")

"""### 30. Faça um programa que receba de um produto:
* o preço
* o tipo (A — alimentação; L — limpeza; e V — vestuário)
* a refrigeração (S — produto que necessita de refrigeração; e N — produto que não necessita de refrigeração) .

**Suponha que haverá apenas a digitação de dados válidos e, quando houver digitação de letras, utilize maiúsculas. Calcule e mostre:**

* O valor adicional, de acordo com a tabela a seguir:

REFRIGERAÇÃO|TIPO|PREÇO|VALOR ADICIONAL
---|---|---|---
N|A|<  15,00|2,00|
 | |>= 15,00|5,00|
 |---------|--------------|-------------------------------
 |L|< 10,00|1,50
 | |>= 10,00|2,50
  |---------|--------------|-------------------------------
 |V|< 30,00|3,00
 ||>= 30,00|2,50
  --------------------------|---------|--------------|-------------------------------
S|A||8,00
|L||0,00
|V||0,00

* O valor do imposto, de acordo com a regra a seguir.

PREÇO|PERCENTUAL SOBRE O PREÇO
---|---
< 25,00|5%
>= 25,00|8%

O preço de custo, ou seja, preço mais imposto.
O desconto, de acordo com a regra a seguir.

O produto que não preencher nenhum dos requisitos a seguir terá desconto de 3%, caso contrário, 0 (zero). Os requisitos são:
* Tipo: A
* Refrigeração: S

* O novo preço, ou seja, preço de custo mais adicional menos desconto.
* A classificação, de acordo com a regra a seguir.

NOVO PREÇO|CLASSIFICAÇÃO
---|---
<= 50,00|Barato
Entre 50,00 e 100,00|Normal
>= 100,00|Caro


```
LEIA pre, tipo, refrig
SE refrig = “N”
    SE tipo = “A”
        SE pre < 15
          valor_adic = 2
        SENÃO 
          valor_adic = 5
    SE tipo = “L”
      SE pre < 10
        valor_adic = 1.5
      SENÃO 
        valor_adic = 2.5
    SE tipo = “V”
      SE pre < 30
        valor_adic = 3
      SENÃO 
        valor_adic = 2.5
SENÃO SE tipo = “A”
    valor_adic = 8
  SE tipo = “L”
    valor_adic = 0
  SE tipo = “V”
    valor_adic = 0
ESCREVA valor_adic
SE pre < 25
  imposto = 5/100 * pré
SENÃO 
  imposto = 8/100 * pre
ESCREVA imposto
pre_custo = pre + imposto
ESCREVA pre_custo
SE tipo != “A” E refrig != “S”
  desconto = 3/100 * pre_custo
SENÃO 
  desconto = 0
ESCREVA desconto
novo_pre = pre_custo + valor_adic – desconto
ESCREVA novo_pre
SE novo_pre <= 50
  ESCREVA “Barato”
SENÃO SE novo_pre < 100
         ESCREVA “Normal”
      SENÃO 
         ESCREVA “Caro”
"""

pre = float(input("Digite o preço do pruduto:"))
tipo = input("Digite os tipos do produto sendo do tipo A(alimentação) L(limpeza) ou V(vestuário), digite letras maiúsculas: ")
refrig = input("se o produto precisa de refrigeração digite a letra S e se não precisa a letra N: ")
if(refrig == "N"): 
    if(tipo == "A"):
        if(pre < 15):
          valor_adic = 2
        else: 
          valor_adic = 5
    elif(tipo == "L"):
      if(pre < 10):
        valor_adic = 1.5
      else: 
        valor_adic = 2.5
    elif(tipo == "V"):
      if(pre < 30):
        valor_adic = 3
      else:
        valor_adic = 2.5
else:
  if(tipo == "A"):
    valor_adic = 8
  elif(tipo == "L"):
    valor_adic = 0
  else:
    valor_adic = 0
print("Escreva o valor adicional em R$",valor_adic)
if(pre < 25):
  imposto = 5/100 * pre
else:
  imposto = 8/100 * pre
print("imposto em R$:",imposto)
pre_custo = pre + imposto
print("pre_custo:", pre_custo)
if(tipo != "A" and refrig != "S"):
  desconto = 3/100 * pre_custo
else: 
  desconto = 0
print("Desconto:",desconto)
novo_pre = pre_custo + valor_adic - desconto
print("Novo preço:",novo_pre)
if(novo_pre <= 50):
   print("Barato")
else: 
     if(novo_pre < 100):
         print("Normal")
     else:
         print("caro")

"""### 31. Faça um programa que receba a medida de um ângulo em graus. Calcule e mostre o quadrante em que se localiza esse ângulo. Considere os quadrantes da trigonometria e, para ângulos maiores que 360° ou menores que −360o, reduzí-los, mostrando também o número de voltas e o sentido da volta (horário ou anti-horário).
```
SE angulo > 360 OU angulo < -360
    voltas = parte inteira(angulo / 360)    
    angulo = RESTO(angulo / 360)
SENÃO 
    voltas = 0
SE angulo = 0 OU angulo = 90 OU angulo = 180
           OU angulo = 270 OU angulo = 360
           OU angulo = -90 OU angulo = -180
           OU angulo = -270 OU angulo = -360
  ESCREVA “Está em cima de algum dos eixos”
  SE (angulo > 0 E angulo < 90) OU (angulo < -270 E angulo > -360)
    ESCREVA “1o Quadrante”
  SE (angulo > 90 E angulo < 180) OU (angulo < -180 E angulo > -270)
    ESCREVA “2o Quadrante”
  SE (angulo > 180 E angulo < 270) OU (angulo < -90 E angulo > -180)
    ESCREVA “3o Quadrante”
  SE (angulo > 270 E angulo < 360) OU (angulo < 0 E angulo > -90)
    ESCREVA “4o Quadrante”
  ESCREVA voltas, “ volta(s) no sentido “
SE angulo < 0
    ESCREVA “horário”
SENÃO 
    ESCREVA “anti-horário”
```
"""

angulo = float(input("Digite a medida do ângulo em graus: "))
if(angulo > 360 or angulo < -360):
    voltas = pa(angulo / 360) // 1    
    angulo = (angulo % 360)
else:
  voltas = 0
  if(angulo == 0 or angulo == 90 or angulo == 180 or angulo == 270 or angulo == 360 or angulo == -90 or angulo == -180or angulo == -270 or angulo == -360):
    print("Está acima de alguns eixos")
  if((angulo > 0 and angulo < 90) or (angulo < -270 and angulo > -360)):
    print("primeiro quadrante")
  elif((angulo > 90 and angulo < 180) or (angulo < -180 and angulo > -270)):
    print("segundo quadrante")
  elif((angulo > 180 and angulo < 270) or (angulo < -90 and angulo > -180)):
    print("Terceiro quadrante")
  elif((angulo > 270 and angulo < 360) or (angulo < 0 and angulo > -90)):
    print("Quatro quadrante")
    print(voltas,"volta(s) no sentido")
if(angulo < 0):
    print("Horário")
else:
    print("Anti-horário")