# -*- coding: utf-8 -*-
"""Keven Escovedo - 20201_Est_Dec_EXTRA_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sfm3ZMM3h6qGqvm6DjEguw94zV0ggpWf

### **LISTA DE EXERCÍCIOS EXTRA PARA ESTUDOS**

###1. Faça um programa que receba a base e a altura de um retangulo e imprimir as seguintes saídas:
perimetro = 2 * (base + altura)

area = base * altura

diagonal = raiz(base ** 2 + altura ** 2)
"""

import math 
base = float(input("por favor digite a base do retangulo:\n"))
altura = float(input("por favor digite a altura do retangulo:\n"))
area = base * altura

diagonal = math.sqrt(base **2 + altura ** 2)
perimetro = 2 * (base + altura)

print("area: ",area)
print("diagonal: ",diagonal)
print("perimetro: ",perimetro)

"""###2. Faça um programa que calcule e mostre o perimetro de um círculo. Sabe-se que perimetro = 2 * pi * raio e o valor da variável pi é 3.1415.
# **New Section**

> **`Indented block`**
"""

raio = float(input("digite o raio do circulo:\n"))
pi = 3.1415
perimetro = 2 * pi * raio
print("o perimetro deste circulo é de:",perimetro)

"""###3. Faça um programa que receba os lados a, b, c de um paralelepípedo. Calcule e mostre a diagonal. Sabe-se que 
diagonal = raiz(a ** 2 + b ** 2 + c ** 2)
"""

import math
a = float(input("digite o numero de um lado:\n"))
b = float(input("digite o numero do segundo lado:\n"))
c = float(input("digite o numero de terceiro lado:\n"))
diagonal = math.sqrt(a **2 + b ** 2 + c ** 2)
print(" a digonal do paralelipido:",diagonal)

"""###4. Faça um programa que receba um número e se ele for maior do 20, mostre a metade do número."""

numero = int(input("digite um numero:\n"))
if numero > 20:
    resultado = numero ** 1/2
    print("a metade de", numero," é:" ,resultado)
else:
    
    print("o numero é menor ou é igual 20")

"""###5. Faça um programa que receba um número e se ele for maior do 20, mostre a metade do número, caso contrário multiplique por 5 e mostre o resultado."""

numero = int(input("digite um numero:\n"))
if numero > 20:
    resultado = numero ** 1/2
    print("a metade de", numero," é:" ,resultado)
else:
    resultado = numero * 5
    print("a multiplicação de", numero,"por 5 é:",resultado)

"""###6. Faça um programa que receba um número, se ele for positivo, mostre seu inverso, caso contrário, mostrar o seu valor absoluto."""

numero = int(input("digite um numero:\n"))
if numero > 0:
    resultado = -(numero)
    
    print("o inverso de", numero,"é:" ,resultado)
    
elif numero == 0:
    print (" o valor obsoluto de 0 é 0")
else:
   resultado = -(numero)
   print (" o valor obsoluto de", numero, "é:",resultado)

"""###7. Faça um programa que receba dois números A e B, se o valor de A for maior que B, inverta-os e apresente-o. Exemplo A = 10, B = 5, resposta A = 5 e B = 10"""

a = float(input("digite um numero:\n"))
b = float(input("digite um ultimo numero:\n"))
if b > a:
    print("A =",a,"B=",b)
else:
    auxiliar = a
    a = b
    b = auxiliar
    print("A =",a,"B=",b)

a = float(input("digite um numero:\n"))
b = float(input("digite um ultimo numero:\n"))
if b > a:
    print("A =",a,"B=",b)
else:
    auxiliar = a
    a = b
    b = auxiliar

"""### 8. Faça um programa que receba um nome de capital, verifique se é a capital do Brasil. Se for mostre "Parabéns", caso sontrário, mostre "Estude mais""""

"""
### 8. Faça um programa que receba um nome de capital, verifique se é a capital do Brasil. Se for mostre "Parabéns", caso sontrário, mostre "Estude mais"


"""
from unicodedata import normalize
capital = input("qual  é  capital do Brasil ?: ")
capital =  capital.casefold()
"""REMOVER ACENTO EM PYTHON"""
capital = normalize('NFKD', capital).encode('ASCII','ignore').decode('ASCII')

if capital == "brasilia" :
    print("parabéns você acetou")
else:
    print("estude mais pois você errou !!!")

"""### 9. Faça um programa que receba uma sigla do estado de uma pessoa e mostre uma das mensagens:
    carioca
    paulista
    mineiro
    outros estados
"""

sigla = input("digite a sigla do seu estado:\n")
sigla =  sigla.casefold()


if sigla == "rj" :
    print("carioca, fala bolacha")
elif sigla == "sp" :
    print("paulista, fala biscoito, fala o meu")

elif sigla == "mg" :
    print("paulista, fala uai, fala trem")
else:
    print("outros estados")

"""### 10. Faça um programa que receba um salário de uma pessoa e mostre o desconto de INSS de acordo com a tabela a seguir

| Valores | Porcentagem |
|---|---|
|Menor ou igual a R$ 600 |	Isento |
| Maior que 600,00 e menor ou igual a 1200,00 | 20% |
|Maior que 1200,00 e menor ou igual a 2000,00 |	30% |
|Maior que 2000,00	|	40% |
"""

salario = float(input("digite o salario de uma pessoa:\n"))
if salario <= 600:
    print ("isento")
elif salario > 600 and salario <= 1200:
  desconto = (salario *(20/100))
  print("deconto do INSS é de:",desconto,"reais")
elif salario > 1200 and salario <= 2000:
  desconto = (salario *(30/100))
  print("deconto do INSS é de:",desconto,"reais")
else:
     desconto =(salario *(40/100))
     print("deconto do INSS é de:",desconto,"reais")