# -*- coding: utf-8 -*-
"""Keven Escovedo - 1L_20201_Alg_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rxhx8wLSKvveU5sYSQw7kYEuZRYiNuyk

### 1. Faça um programa que leia um número, multiplique ele por 2 e apresente o resultado.
      LEIA numero
      resultado = numero * 2
      ESCREVA resultado
"""

numero = float(input("Por favor digite um número: "))
                
resultado = numero * 2
print("o resultado de",numero,"multiplicado por 2 é:",resultado)

"""### 2. Faça um programa que:
* receba quatro números inteiros
* calcule e mostre a soma desses números.


    LEIA n1, n2, n3, n4    
    soma = n1 + n2 + n3 + n4  
    ESCREVA soma
"""



numero1 = int(input("Por favor digite um número: "))
numero2 = int(input("Por favor digite um segundo número: "))
numero3 = int(input("Por favor digite um terceiro número: "))
numero4= int(input("Por favor digite um quarto número: "))               
resultado = numero1 + numero2 + numero3 + numero4
print("o resultado de ", " o resultado soma dos quatros numeros escolhidos por você é: ",resultado)

"""### 3. Faça um programa que receba três notas, calcule e mostre a média aritmética.
      LEIA nota1, nota2, nota3
      media = (nota1 + nota2 + nota3) / 3
      ESCREVA media
"""

nota1 = float(input("Por favor escreva a primeira  nota do aluno: "))
nota2 = float(input("Por favor escreva a Segunda nota do aluno: "))
nota3 = float(input("Por favor escreva a terceira nota do aluno: "))
media = (nota1 +  nota2 + nota3)/ 3
if(media >= 6.0 ):
          print("a média do aluno foi de: ",media,"por isso foi aprovado")
else:
   print("a media do aluno foi de: ",media,"por isso ele está reprovado")

"""### 4. Faça um programa que:
* receba o salário de um funcionário
* calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%.

      LEIA salario
      novoSalario = salario + (salario * 25 / 100)
      ESCREVA novoSalario
"""

salario = float(input("Por favor informe o salário de um funcionário em R$: "))
novo_salario = salario + (salario * 25/100)
print("O novo salário do funcionário é:",novo_salario)

"""### 5. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário.

      LEIA salario, percentual
      aumento = salario * percentual/100
      ESCREVA aumento
      novo_salario = salario + aumento
      ESCREVA novo_salario
"""

salario = float(input("Por favor informe o salário de um funcionário em R$: "));
percentual = float(input("Por favor informe o percentual de aumento: "))
aumento = salario * percentual/100
print("O aumento foi de: ", aumento)
novo_salario = salario + aumento
print("O novo salário do funcionário foi em R$: ",novo_salario)

"""### 6. Faça um programa que receba o salário base de um funcionário, calcule e mostre o salário a receber, sabendo-se que o funcionário tem gratificação de 5% sobre o salário base e paga imposto de 7% também sobre o salário base.

    LEIA salario
    gratificacao = salario * 5 / 100
    imposto = salario * 7 / 100
    salario_a_receber ← salario + gratificacao − imposto
    ESCREVA salrario_a_receber
"""

salario = float(input("Por favor infome o salário base do funcionário em R$: "))
gratificacao = salario * 5/100
imposto = salario * 7/100
salario_a_receber = salario + gratificacao - imposto
print("O salário que o funcionário deve receber é de em R$: ",salario_a_receber)

"""### 7. Faça um programa que receba o salário base de um funcionário, calcule e mostre seu salário a receber, sabendo-se que o funcionário tem gratificação de 50,00 sobre o salário base e paga imposto que deve ser lido e é aplicado sobre o salário base.

    LEIA salario, perImposto
    imposto = salario * perImposto / 100
    salario_a_receber = salario + 50 - imposto
    ESCREVA salario_a_receber
"""

salario = float(input("Por favor infome o salario base do funcionário em R$: "))
perImposto = float(input("Por favor infome o perImposto: "))
imposto = salario * perImposto/100
salario_a_receber= salario + 50 - imposto
print("O salário que o funcionário deve receber é de em R$: ",salario_a_receber)

"""### 8. Faça um programa que receba o valor de um depósito e o valor da taxa de juros, calcule e mostre o valor do rendimento e o valor total depois do rendimento de um mês.

      LEIA deposito, taxa
      rendimento = deposito * taxa / 100
      total = deposito + rendimento
      ESCREVA rendimento
      ESCREVA total
"""

deposito = float(input("Por favor infome um depósito em R$: "))
taxa = float(input("Por favor infome uma taxa: "))
rendimento =  deposito * taxa/100
total = deposito + rendimento
print("O Rendimento é de em R$: ", rendimento)
print("O total é de em R$:", total)

"""### 9. Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: Área = (base * altura) / 2.

    LEIA base, altura
    area = (base * altura) / 2
    ESCREVA area
"""

base = float(input("Por favor infome a base de um trinângulo: "))
altura = float(input("Por favor infome a altura do triângulo: "))
area = (base * altura) / 2
print("A área deste trinângulo é de: ",area)

"""### 10. Faça um programa que calcule e mostre a área de um círculo. Sabe-se que: Área = pi * R 2 (este 2 significa elevado ao quadrado) e o valor da variável pi é 3.1415.
    LEIA raio
    area = 3.1415 * raio ** 2
    ESCREVA area
"""

raio = float(input("Por favor informe o raio de um círculo: "))
area = 3.1415 * raio ** 2
print("A área deste círculo é de:",area)

"""### 11. Faça um programa que receba um número positivo e maior que zero, calcule e mostre:
* O número digitado ao quadrado
* O número digitado ao cubo
* A raiz do número digitado
* A raiz cúbica do número digitao

      LEIA numero
      quadrado = numero ** 2
      cubo = numero ** 3
      raiz_quadrada = numero ** ½ (elevado a meio)
      raiz_cubica = numero ** ⅓ (elevado ao um terço)
      ESCREVA quadrado, cubo, raiz_quadrada, raiz_cubica

**Observação**: o valor que esta na variável raiz_quadra após o operador ** é um sobre dois (meio) e na variável raiz_cubica é um terço
"""

# Digite seu código aqui.

numero = float(input('Por favor digite um número: '))
if(numero > 0):
         quadrado = numero ** 2
         cubo = numero ** 3
         raiz_quadrada = numero ** (1/2)
         raiz_cubica = numero **(1/3)
         print(numero," elevado ao quadrado é igual a: ",quadrado)
         print(numero," elevado ao cúbo é igual a: ",cubo)
         print("a raiz quadrada de ",numero, "é igual a: ",raiz_quadrada)
         print("a raiz cúbica de ",numero, "é igual a: ",raiz_cubica)
else:
 print("Por favor digite um numero maior que zero ")

"""### 12. Faça um programa que receba dois números maiores que zero, calcule e mostre um elevado ao outro.

      LEIA numero1, numero2
      numero1_elevado_numero2 = numero1 ** numero2
      numero2_elevado_numero1 = numero2 ** numero1
      ESCREVA numero1_elevado_numero2, numero2_elevado_numero1
"""

numero1 = float(input('Por favor digite um número: '))
numero2 = float(input("Por favor informe um segundo número: "))
if(numero > 0):
        numero1_elevado_numero2 = numero1 ** numero2
        numero2_elevado_numero1 = numero2 ** numero1
        print(numero1," elevado a", numero2,"é igual a: ",numero1_elevado_numero2)
        print(numero2," elevado a",numero1, "é igual a: ", numero2_elevado_numero1)
         
else:
 print("Por favor digite um numero maior que zero ")

"""### 13. Sabe-se que:

* pé = 12 polegadas
* 1 jarda = 3 pés
* 1 milha = 1,760 jarda

Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.

* Polegadas;
* Jardas;
* Milhas.

      LEIA pes
      polegadas = pes * 12
      jardas = pes / 3
      milhas = jardas / 1760
      ESCREVA polegadas, jardas, milhas
"""

pes = float(input("Por favor informe uma numero em pé: "))
# 
polegadas = pes * 12
jardas = pes / 3
milhas = jardas  / 1.760
print("Polegadas: ",polegadas)
print("Jardas: ",jardas)
print("Milhas: ", milhas)

"""### 14. Faça um programa que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:
* a idade dessa pessoa;
* quantos anos ela terá em 2050.
      LEIA ano_atual
      LEIA ano_nascimento
      idade_atual = ano_atual − ano_nascimento
      idade_2050 = 2050 − ano_nascimento
      ESCREVA idade_atual
"""

ano_atual = int(input("Por favor informe o ano em que estamos: "))
ano_nascimento = int(input("Por favor informe o ano do seu nascimento: "))
idade_atual = ano_atual - ano_nascimento
idade_2050 = 2050 - ano_nascimento
print("Você possui",idade_atual,"anos de idade")
print("Em 2050 você terá",idade_2050,"de idade")

"""#### 15. O custo ao consumidor de um carro novo é a soma do preço de fábrica com o percentual de lucro do distribuidor e dos impostos aplicados ao preço de fábrica. Faça um programa que receba o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:
* o valor correspondente ao lucro do distribuidor;
* o valor correspondente aos impostos;
* o preço final do veículo.
        LEIA preco_de_fabrica
        LEIA percentual_de_lucro_do_distribuidr
        LEIA percentual_do_imposto
        lucro_do_distribuidor = preco_de_fabrica *
              percentual_de_lucro_do_distribuido / 100
        valor_do_imposto = preco_de_fabrica * 
              percentual_de_imposto / 100
        preco_final =  preco_de_fabrica + lucro_do_distribuidor +
              valor_do_imposto
        ESCREVA lucro_do_distribuidor
        ESCREVA valor_do_imposto
        ESCREVA preco_final
"""

preco_fabrica = float(input("Por favor digite o preço de fabrica do carro em R$: "))
percentual_de_lucro_do_distribuidor = float(input("Por favor digite o percentual de lucro do distribuidor: "))
percentual_do_imposto = float(input("Por favor digite o percentual de imposto: "))
lucro_do_distribuidor = preco_fabrica * percentual_de_lucro_do_distribuidor/100
valor_do_imposto = preco_fabrica * percentual_do_imposto/100
preco_final = preco_fabrica + lucro_do_distribuidor + valor_do_imposto
print("O lucro do distribuidor será dem em R$:",lucro_do_distribuidor)
print("O valor do imposto em R$ é de:",valor_do_imposto)
print("O preço final do carro é dem em R$:",preco_final)

"""### 16. Faça um programa que receba o número de horas trabalhadas e o valor do salário mínimo, calcule e mostre o salário a receber, seguindo estas regras:
* a hora trabalhada vale a metade do salário mínimo.
* o salário bruto equivale ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
* o imposto equivale a 3% do salário bruto.
* o salário a receber equivale ao salário bruto menos o imposto.
      LEIA quantidade_de_horas_trabalhadas
      LEIA valor_do_salario_minimo
      valor_hora_trabalhada = valor_do_salario_minimo / 2
      valor_salario_bruto = valor_da_hora_trabalhada *
            quantidade_de_horas_trabalhadas
      impostos = valor_salario_bruto * 3 / 100
      Valor_salario_liquido =  ← valor_salario_bruto - impostos
          ESCREVA valor_salario_liquido
"""

quantidade_de_horas_trabalhadas = int(input("Por favor digite a quantidade de horas trabalhadas pelo funcionário, somente horas: "))
valor_salario_minimo = float(input("Por favor digite o salario minímo do funcionário em R$: "))
valor_hora_trabalhada = valor_salario_minimo/2
valor_salario_bruto = valor_hora_trabalhada * quantidade_de_horas_trabalhadas
impostos = valor_salario_bruto * 3/100
valor_salario_liquido = valor_salario_bruto - impostos
print("O salário a ser recebido pelo funcionário é de em R$:",valor_salario_bruto)

"""### 17. Um trabalhador recebeu seu salário e o depositou em sua conta bancária. Esse trabalhador emitiu dois cheques e agora deseja saber seu saldo atual. O banco criou uma taxa para a operação bancária de retirada que tem que pagar um imposto, chamado de cpmf, de 0.38% e o saldo inicial da conta está zerado.

      LEIA salario
      LEIA valor_cheque1
      LEIA valor_cheque2
      cpmf_cheque1 = valor_cheque1 * 0.038 / 100
      saque1 = valor_cheque1 + cpmf_cheque1
      cpmf_cheque2 = cheque2 * 0.038 / 100
      saque2 = valor_cheque2 + cpmf_cheque2
      saldo = salario - saque1 - saque2
      ESCREVA saldo
"""

salario = float(input("Por favor digite um sálario da conta bancária em R$: "))
valor_cheque1 = float(input("Por favor digite o valor do primeiro cheque em R$: "))
valor_cheque2 = float(input("Por favor digite o valor do primeiro cheque em R$: "))
cpmf_cheque1 = valor_cheque1 * 0.38/100
saque1 = valor_cheque1 + cpmf_cheque1
cpmf_cheque2 = valor_cheque2 * 0.38/100
saque2 = valor_cheque2 + cpmf_cheque2
saldo = salario - saque1 - saque2
print("O saldo bancário é de em R$",saldo)

"""### 18. Pedro comprou um saco de ração com peso em quilos. Ele possui dois gatos, para os quais fornece a quantidade de ração em gramas. A quantidade diária de ração fornecida para cada gato é sempre a mesma. Faça um programa que receba o peso do saco de ração e a quantidade de ração fornecida para cada gato, calcule e mostre quanto restará de ração no saco após cinco dias.

      LEIA peso_saco
      LEIA racao_gato1
      LEIA racao_gato2
      Racao_gato1 = racao_gato1 / 1000
      racao_gato2 = racao_gato2 / 1000
      total_final = peso_saco − 5 * (racao_gato1 + racao_gato2)
      ESCREVA total_final
"""

peso_saco = float(input("Digite o peso do saco em quilos: "))
racao_do_gato1 = float(input("Digite a quantidade de gramas da ração fornecida para o gato 1: "))
racao_do_gato2 = float(input("Digite a quantidade de gramas da ração fornecida para o gato 2: "))
racao_do_gato1emkg = racao_do_gato1/1000
racao_do_gato2emkg = racao_do_gato2/1000
total_final = peso_saco - 5 *(racao_do_gato1emkg + racao_do_gato2emkg)
print("A quantidade de ração no quinto dia é de", total_final,"quilos")

"""### 19. Cada degrau de uma escada tem X de altura. Faça um programa que receba essa altura e a altura que o usuário deseja alcançar subindo a escada, calcule e mostre quantos degraus ele deverá subir para atingir seu objetivo, sem se preocupar com a altura do usuário. Todas as medidas fornecidas devem estar em metros.
      LEIA altura_do_degrau
      LEIA altura_desejada
      quantidade_de_degraus = altura_desejada // altura_do_degrau
      ESCREVA quantidade_degraus
**Observação**: o operador **//** em Python é utilizado para pegar a parte inteira de uma divisão
"""

altura_do_degrau = float(input("digite a altura do degrau em metros: "))
altura_desejada = float(input("digite altura que você deseja chegar em metros: "))
quantidade_de_degraus = altura_desejada // altura_do_degrau
print("A quantidade de degraus que você  precisa para atingir a altura de",altura_desejada,"metros é de",quantidade_de_degraus,"degraus")

"""### 20. Faça um programa que receba a medida do ângulo (em graus) formado por uma escada apoiada no chão e encostada na parede e a altura da parede onde está a ponta da escada. Calcule e mostre a medida dessa escada. Observação: as funções trigonométricas implementadas nas linguagens de programação trabalham com medidas de ângulos em radianos.
      LEIA angulo
      LEIA altura
      radiano = angulo * 3.14 / 180
      escada = altura / seno(radiano)
      ESCREVA escada
**Observação**: Para usar seno em Python, deve-se usar esta linha de código **import math** e esta outra linha, no cálculo, **math.sin(número)**.
"""

angulo =  float(input("Digite a medida do ângulo em graus: "))
altura = float(input("informe a altura da parade onde está encostada a escada: "))
radiano =angulo * 3.14/180
import math
escada = altura/math.sin(radiano)
print("a medida desta escada é de:",escada)

"""### 21. Uma pessoa deseja pregar um quadro em uma parede. Faça um programa para calcular e mostrar a que distância a escada deve estar da parede. A pessoa deve fornecer o tamanho da escada e a altura em que deseja pregar o quadro. Lembre-se de que o tamanho da escada deve ser maior que a altura que se deseja alcançar.
      LEIA Z
      LEIA X
      Y = Z ** 2 - X ** 2
      Y = Y **1/2
      ESCREVA Y
"""

z = float(input("Por favor digite o tamanho da escada que deve ser maior que altura desejada, digite em metros: "))
x =  float(input("Por favor digite altura que você deseja pregar o quadro, digite em metros: "))
y = z ** 2 - x ** 2
y = y ** 1/2
print("A escada deve estar á",y,"metros de distância da parede")

"""###22. Sabe-se que o quilowatt de energia custa um quinto do salário mínimo. Faça um programa que receba o valor do salário mínimo e a quantidade de quilowatts consumida por uma residência. Calcule e mostre:


* o valor de cada quilowatt;
* o valor a ser pago por essa residência;
* o valor a ser pago com desconto de 15%.
      LEIA valor_do_salario
      LEIA quantidade_de_quilowatt
      valor_do_quilowatt = valor_do_salario / 5
      valor_em_reais ← valor_do_quilowatt * qquantidade_de_quilowatt
      valor_do_desconto = valor_em_reais * 15 / 100
      valor_com_desconto =  valor_em_reais − valor_do_desconto
      ESCREVA valor_do_quilowatt
      ESCREVA valor_em_reais
      ESCREVA valor_com_desconto
"""

valor_salario = float(input('Por favor digite o salário minimo: '))
quantidade_de_quilowatt = float(input("Digite a quantidade de quilowatt consumido por residência, virgulas em lugar de ponto: "))
valor_do_quilowatt = valor_salario / 5
valor_em_reais = valor_do_quilowatt * quantidade_de_quilowatt
valor_do_desconto = valor_em_reais * 15/100
valor_com_desconto =valor_em_reais - valor_do_desconto
print(" O valor do quilowatt é de: ",valor_do_quilowatt)
print("O valor em R$ é de: ",valor_em_reais)
print("O valor com desconto em R$ é de: ", valor_com_desconto)

"""### 23. Faça um programa que receba um número real, encontre e mostre:

* a parte inteira desse número;
* a parte fracionária desse número;
* o arredondamento desse número.

      LEIA numero
      parte_inteira = numero // 1
      parte_fracionaria = numero - parte_inteira
      numero_arredondado = arredonda (numero)
      ESCREVA parte_inteira
      ESCREVA parte_fracionaria
      ESCREVA numero_arredondado
      
**Observação**: Para arredondar um número em Python, usa-se a função **round(numero)**, onde se o número real/float estiver em igual distância entre o inteiro de cima e o inteiro de baixo, esta função arredonda para o número par mais próximo.
"""

numero = float(input("Por favor informe um numero real: "))
parte_inteira = numero//1
parte_fracionaria = numero - parte_inteira
numero_arrendonado = round(numero)
print("A parte inteira:",parte_inteira)
print("A parte fracionária:",parte_fracionaria)
print("Numero arrendondado:",numero_arrendonado)

"""### 24. Faça um programa que receba uma hora formada por hora e minutos (um número real), calcule e mostre a hora digitada apenas em minutos. Lembre-se de que:
* para quatro e meia, deve-se digitar 4.30;
* os minutos vão de 0 a 59.
      LEIA hora
      h = pegar a parte inteira da variável hora
      minutos = hora − h
      conversao = (h * 60) + (minutos * 100)
      ESCREVA conversao
"""

hora = float(input("Por favor digite uma hora formadas por hora e minutos ex 7.40: "))
h =  hora//1
minutos  = hora - h
conversao = (h * 60) + (minutos * 100)
conversao = round(conversao)
print(hora, "é igual a",conversao,"minutos")

"""### 25. Faça um programa que receba o custo de um espetáculo teatral e o preço do convite desse espetáculo. Esse programa deverá calcular e mostrar a quantidade de convites que devem ser vendidos para que, pelo menos, o custo do espetáculo seja alcançado.

      LEIA custo
      LEIA convite
      quantidade = custo / convite
      ESCREVA quantidade
"""

custo = float(input("Por favor digite o preço do espetáculo teatral em R$: "))
convite = float(input("Por favor digite o preço do convite em R$: "))
quantidade = custo/convite
quantidade = round(quantidade)
print("A quantidade de convites necessario para atingir o preço total da peça que é de", custo,"é",quantidade,"convites")